import type { ScenarioId, SoundLifeArchetype } from "./types";

const ALL_SCENARIOS: ScenarioId[] = [
  "drive",
  "gym",
  "focus",
  "party",
  "sad",
  "chill",
  "random",
];

export const SOUNDLIFE_ARCHETYPES: SoundLifeArchetype[] = [
  {
    id: "gym-villain-arc",
    name: "Gym Villain Arc",
    requiredTraits: ["aggression", "confidence", "energy"],
    preferredScenarios: ["gym"],
    preferredGenres: ["hip-hop", "metal", "edm", "techno"],
    blockedGenres: ["country", "folk", "lo-fi"],
    preferredLanguages: ["english", "instrumental"],
    diagnosis: "You do not work out. You enter a private revenge montage with better percussion.",
    softCopy: "Your gym music wants momentum, focus, and a tiny bit of cinematic menace.",
    accurateCopy: "We regret to inform you the final rep has become personal and the mirror is now a supporting character.",
    roastCopy: "You heard one bass drop and started training like your ex is judging form from the squat rack.",
    bestFor: "Heavy lifts, sprint finishes, walking into the gym like the lighting changed.",
    dangerousAround: "A quiet stretch room, fragile headphones, anyone using the phrase light warmup.",
    shareCaption: "My SoundLife says I am in my Gym Villain Arc.",
    colorTheme: { background: "#190A0A", accent: "#DC2626", text: "#FFF7ED" },
    emoji: "😈",
    sticker: "🥊",
  },
  {
    id: "tokyo-night-drive",
    name: "Tokyo Night Drive",
    requiredTraits: ["cinematic", "darkness", "tempo"],
    preferredScenarios: ["drive", "focus"],
    preferredGenres: ["j-pop", "edm", "techno", "pop"],
    blockedGenres: ["country", "folk"],
    preferredLanguages: ["japanese", "instrumental"],
    diagnosis: "Your brain wants neon, motion blur, and one emotionally irresponsible lane change.",
    softCopy: "You like songs that make ordinary travel feel expensive and slightly fictional.",
    accurateCopy: "This is suspiciously accurate because you treat a night drive like free therapy with better lighting.",
    roastCopy: "You saw one reflection in a rainy window and immediately became the lead in a movie nobody greenlit.",
    bestFor: "Late drives, train windows, city walks, pretending your commute has a soundtrack budget.",
    dangerousAround: "Open highways, unread texts, anyone who says just put on something normal.",
    shareCaption: "Apparently my inner life is Tokyo Night Drive.",
    colorTheme: { background: "#111827", accent: "#A855F7", text: "#F8FAFC" },
    emoji: "🗼",
    sticker: "🌃",
  },
  {
    id: "velvet-chaos",
    name: "Velvet Chaos",
    requiredTraits: ["softness", "chaos", "romance"],
    preferredScenarios: ["chill", "sad", "party", "random"],
    preferredGenres: ["r&b", "pop", "indie", "lo-fi"],
    blockedGenres: ["metal"],
    preferredLanguages: ["english", "french", "spanish"],
    diagnosis: "Soft voice, unstable plot. You want the song pretty, but not emotionally insured.",
    softCopy: "Your taste is gentle on the surface and a little messy underneath.",
    accurateCopy: "You are legally required to pick beautiful songs that sound like they know too much.",
    roastCopy: "You want calm music for the exact kind of life choices that make calm music impossible.",
    bestFor: "Texting back after three business days, soft outfits, dramatic errands.",
    dangerousAround: "Old voice notes, mutual friends, aesthetically lit bad decisions.",
    shareCaption: "Velvet Chaos is not a phase. It is a scheduling problem.",
    colorTheme: { background: "#3B1027", accent: "#F472B6", text: "#FFF1F2" },
    emoji: "🥀",
    sticker: "🧃",
  },
  {
    id: "main-character-damage",
    name: "Main Character Damage",
    requiredTraits: ["confidence", "cinematic", "romance"],
    preferredScenarios: ["drive", "sad", "party", "random"],
    preferredGenres: ["pop", "r&b", "hip-hop", "indie"],
    blockedGenres: ["lo-fi"],
    preferredLanguages: ["english", "korean", "spanish"],
    diagnosis: "The soundtrack arrived before the character development, and honestly that tracks.",
    softCopy: "You like music with scale, feeling, and a little spotlight energy.",
    accurateCopy: "We regret to inform you the problem was never the playlist. It was the plot you assigned to the playlist.",
    roastCopy: "You cannot walk through a parking lot without making it an Act Two turning point.",
    bestFor: "Leaving events early, dramatic walks, outfit checks, pretending the camera found you.",
    dangerousAround: "Mirrors, stairs, elevators, songs with a slow-motion chorus.",
    shareCaption: "My SoundLife diagnosed me with Main Character Damage.",
    colorTheme: { background: "#24111F", accent: "#FB7185", text: "#FFF7ED" },
    emoji: "🎬",
    sticker: "🔥",
  },
  {
    id: "sunset-soft-launch",
    name: "Sunset Soft Launch",
    requiredTraits: ["warmth", "softness", "romance"],
    preferredScenarios: ["chill", "drive", "sad"],
    preferredGenres: ["r&b", "afrobeats", "indie", "folk"],
    blockedGenres: ["metal", "techno"],
    preferredLanguages: ["english", "spanish", "portuguese"],
    diagnosis: "You want the aux to feel golden, low pressure, and suspiciously photogenic.",
    softCopy: "Your music likes warmth, space, and a little harmless romance.",
    accurateCopy: "This result knows you would soft launch a feeling before admitting it has a name.",
    roastCopy: "You call it a chill playlist, then choose songs that look directly at the person in the passenger seat.",
    bestFor: "Golden hour drives, beach walks, clean rooms, making eye contact for half a second too long.",
    dangerousAround: "Shared sunsets, vacation photos, anyone you are pretending not to like.",
    shareCaption: "Sunset Soft Launch found me and asked for lighting.",
    colorTheme: { background: "#3B2412", accent: "#F59E0B", text: "#FFFBEB" },
    emoji: "🌅",
    sticker: "🏖️",
  },
  {
    id: "afrobeats-sunshine",
    name: "Afrobeats Sunshine",
    requiredTraits: ["warmth", "tempo", "energy"],
    preferredScenarios: ["party", "chill", "drive", "random"],
    preferredGenres: ["afrobeats", "amapiano", "r&b"],
    blockedGenres: ["metal"],
    preferredLanguages: ["english", "portuguese"],
    diagnosis: "Your nervous system believes groove is a public utility.",
    softCopy: "You like warm rhythm, easy movement, and songs that unlock the room.",
    accurateCopy: "Your aux privileges include making everyone less stiff within thirty seconds.",
    roastCopy: "You heard one log drum and immediately became impossible to seat at brunch.",
    bestFor: "Day parties, warm-ups, kitchen dancing, turning errands into a small parade.",
    dangerousAround: "A bad speaker, people who clap on one and three, low-energy group chats.",
    shareCaption: "My SoundLife is Afrobeats Sunshine. Correct.",
    colorTheme: { background: "#11332B", accent: "#F59E0B", text: "#ECFDF5" },
    emoji: "🌍",
    sticker: "☀️",
  },
  {
    id: "soft-chaos",
    name: "Soft Chaos",
    requiredTraits: ["softness", "chaos"],
    preferredScenarios: ALL_SCENARIOS,
    preferredGenres: ["r&b", "pop", "lo-fi", "indie"],
    blockedGenres: ["metal"],
    preferredLanguages: ["english", "korean", "french"],
    diagnosis: "Everything is fine, except for the tiny emotional weather system under the hoodie.",
    softCopy: "You like gentle songs with just enough instability to feel personal.",
    accurateCopy: "This is suspiciously accurate because you keep choosing soft sounds with unstable subtext.",
    roastCopy: "You want music that says I am healing while actively opening the app you should not open.",
    bestFor: "Cleaning your room halfway, overexplaining, sitting on the floor for clarity.",
    dangerousAround: "Old texts, shared playlists, a blank Notes app at midnight.",
    shareCaption: "Soft Chaos is my official audio diagnosis.",
    colorTheme: { background: "#31203A", accent: "#F9A8D4", text: "#FAF5FF" },
    emoji: "🌸",
    sticker: "🌀",
  },
  {
    id: "luxury-meltdown",
    name: "Luxury Meltdown",
    requiredTraits: ["confidence", "chaos", "cinematic"],
    preferredScenarios: ["party", "sad", "gym", "random"],
    preferredGenres: ["hip-hop", "pop", "r&b", "edm"],
    blockedGenres: ["folk", "lo-fi"],
    preferredLanguages: ["english", "french", "korean"],
    diagnosis: "Champagne taste, emergency emotions, soundtrack immaculate.",
    softCopy: "Your taste wants glamour with a little emotional static.",
    accurateCopy: "You are legally required to make the meltdown look styled.",
    roastCopy: "You are one bassline away from saying actually I'm fine in designer lighting.",
    bestFor: "Getting ready, revenge outfits, elevator exits, spending too long on one photo.",
    dangerousAround: "Flash photography, group dinners, anyone who asks are you okay too directly.",
    shareCaption: "Luxury Meltdown. Expensive problem, excellent playlist.",
    colorTheme: { background: "#21180A", accent: "#D97706", text: "#FFFBEB" },
    emoji: "💎",
    sticker: "🫠",
  },
  {
    id: "rainy-window-syndrome",
    name: "Rainy Window Syndrome",
    requiredTraits: ["softness", "darkness", "romance"],
    preferredScenarios: ["sad", "focus", "chill", "drive"],
    preferredGenres: ["lo-fi", "indie", "r&b", "jazz"],
    blockedGenres: ["edm", "metal"],
    preferredLanguages: ["english", "japanese", "korean", "thai"],
    diagnosis: "You do not experience weather. You curate it emotionally.",
    softCopy: "You like soft sadness, slow detail, and songs that make quiet feel full.",
    accurateCopy: "This result knows you can turn a drizzle into a full limited series.",
    roastCopy: "You saw rain on glass and immediately prepared a mental slideshow of events from 2019.",
    bestFor: "Rainy commutes, studying, quiet heartbreak, pretending you are not checking the forecast.",
    dangerousAround: "Window seats, gray skies, acoustic covers, unsent messages.",
    shareCaption: "Rainy Window Syndrome got me. I need a blanket.",
    colorTheme: { background: "#102033", accent: "#60A5FA", text: "#EFF6FF" },
    emoji: "🌧️",
    sticker: "🪟",
  },
  {
    id: "club-goblin",
    name: "Club Goblin",
    requiredTraits: ["energy", "chaos", "tempo"],
    preferredScenarios: ["party", "gym", "random"],
    preferredGenres: ["edm", "techno", "amapiano", "reggaeton"],
    blockedGenres: ["acoustic", "folk", "classical"],
    preferredLanguages: ["english", "spanish", "instrumental"],
    diagnosis: "The function is not ready for your relationship with percussion.",
    softCopy: "Your taste wants movement, impact, and a room that gives up on sitting down.",
    accurateCopy: "Your aux privileges include ignoring the concept of a reasonable volume.",
    roastCopy: "You hear a kick drum and start acting like the lease allows this.",
    bestFor: "Packed rooms, late arrivals, cardio disguised as socializing.",
    dangerousAround: "Glass tables, quiet lounges, neighbors with a phone number.",
    shareCaption: "Club Goblin has entered the group chat.",
    colorTheme: { background: "#0B1720", accent: "#22D3EE", text: "#ECFEFF" },
    emoji: "🪩",
    sticker: "🔊",
  },
  {
    id: "heartbreak-cinematic-universe",
    name: "Heartbreak Cinematic Universe",
    requiredTraits: ["romance", "cinematic", "darkness"],
    preferredScenarios: ["sad", "drive", "chill"],
    preferredGenres: ["r&b", "pop", "indie", "thai-pop"],
    blockedGenres: ["metal", "edm"],
    preferredLanguages: ["english", "thai", "korean", "spanish"],
    diagnosis: "Every feeling gets a sequel, a prequel, and one song that hurts on purpose.",
    softCopy: "Your taste makes heartbreak big, beautiful, and easier to sit with.",
    accurateCopy: "We regret to inform you the lore is deeper than the relationship was.",
    roastCopy: "You do not move on. You expand the franchise.",
    bestFor: "Crying in high definition, long drives, staring at one photo too long.",
    dangerousAround: "Anniversaries, suggested memories, anyone whose name still changes the room.",
    shareCaption: "My SoundLife joined the Heartbreak Cinematic Universe.",
    colorTheme: { background: "#2A1020", accent: "#DB2777", text: "#FDF2F8" },
    emoji: "💔",
    sticker: "🎞️",
  },
  {
    id: "clean-girl-villain",
    name: "Clean Girl Villain",
    requiredTraits: ["confidence", "focus", "softness"],
    preferredScenarios: ["focus", "gym", "chill"],
    preferredGenres: ["r&b", "pop", "jazz", "instrumental"],
    blockedGenres: ["metal"],
    preferredLanguages: ["english", "french", "instrumental"],
    diagnosis: "Calm surface, locked calendar, playlist with boundaries.",
    softCopy: "Your taste is polished, focused, and quietly difficult to impress.",
    accurateCopy: "Do not play this around anyone who thinks low maintenance means low standards.",
    roastCopy: "You put on lip balm and suddenly started enforcing international law in the group chat.",
    bestFor: "Pilates walks, focused work, expensive errands, leaving on time.",
    dangerousAround: "Messy plans, cheap candles, people who say just wing it.",
    shareCaption: "Clean Girl Villain is a lifestyle and a warning.",
    colorTheme: { background: "#F8FAFC", accent: "#0F766E", text: "#0F172A" },
    emoji: "🧼",
    sticker: "👑",
  },
  {
    id: "golden-retriever-basshead",
    name: "Golden Retriever Basshead",
    requiredTraits: ["energy", "warmth", "confidence"],
    preferredScenarios: ["party", "gym", "drive", "random"],
    preferredGenres: ["hip-hop", "edm", "afrobeats", "reggaeton"],
    blockedGenres: ["lo-fi", "classical"],
    preferredLanguages: ["english", "spanish", "portuguese"],
    diagnosis: "Friendly face, reckless subwoofer choices.",
    softCopy: "Your taste is bright, big, and generous with the bass.",
    accurateCopy: "Your aux privileges include making the room happier and mildly louder than requested.",
    roastCopy: "You are emotionally sunny until the bass hits, then suddenly the furniture is in danger.",
    bestFor: "Road trips, pre-games, cleaning with friends, making shy people nod along.",
    dangerousAround: "Rental cars, paper-thin walls, anyone who says keep it low.",
    shareCaption: "Golden Retriever Basshead feels offensively accurate.",
    colorTheme: { background: "#2A1C08", accent: "#FBBF24", text: "#FFFBEB" },
    emoji: "☀️",
    sticker: "🔊",
  },
  {
    id: "quiet-storm",
    name: "Quiet Storm",
    requiredTraits: ["focus", "darkness", "softness"],
    preferredScenarios: ["focus", "drive", "chill", "sad"],
    preferredGenres: ["r&b", "jazz", "instrumental", "lo-fi"],
    blockedGenres: ["metal", "edm"],
    preferredLanguages: ["english", "instrumental", "french"],
    diagnosis: "Low volume, high emotional precision. Nobody notices until the room changes.",
    softCopy: "Your taste prefers depth over noise and texture over performance.",
    accurateCopy: "This is suspiciously accurate because you choose quiet songs that still win the argument.",
    roastCopy: "You call it calm because brooding quietly sounds less dramatic.",
    bestFor: "Deep work, night routines, solo drives, saying less and meaning more.",
    dangerousAround: "People who need constant stimulation, fluorescent lighting, loud notifications.",
    shareCaption: "Quiet Storm. Low volume, high consequence.",
    colorTheme: { background: "#111827", accent: "#38BDF8", text: "#F8FAFC" },
    emoji: "🌘",
    sticker: "🌩️",
  },
  {
    id: "neon-overthinker",
    name: "Neon Overthinker",
    requiredTraits: ["cinematic", "darkness", "focus"],
    preferredScenarios: ["drive", "focus", "sad"],
    preferredGenres: ["edm", "j-pop", "pop", "instrumental"],
    blockedGenres: ["country"],
    preferredLanguages: ["japanese", "english", "instrumental"],
    diagnosis: "Your brain has LED lighting and too many tabs open.",
    softCopy: "You like sharp, nocturnal songs that keep the thoughts moving in formation.",
    accurateCopy: "We regret to inform you the overthinking has excellent production value.",
    roastCopy: "You built a whole thesis from one message bubble and gave it a synth line.",
    bestFor: "Late work, night walks, city transit, making one decision after 47 internal meetings.",
    dangerousAround: "Read receipts, caffeine after 5pm, open-ended plans.",
    shareCaption: "Neon Overthinker. Unfortunately, yes.",
    colorTheme: { background: "#101324", accent: "#C084FC", text: "#F5F3FF" },
    emoji: "🌃",
    sticker: "🧠",
  },
  {
    id: "festival-menace",
    name: "Festival Menace",
    requiredTraits: ["energy", "tempo", "chaos"],
    preferredScenarios: ["party", "gym"],
    preferredGenres: ["edm", "amapiano", "reggaeton", "pop"],
    blockedGenres: ["acoustic", "folk", "lo-fi"],
    preferredLanguages: ["english", "spanish", "instrumental"],
    diagnosis: "You do not need a stage. You need thirty feet of space and a forgiving group chat.",
    softCopy: "Your taste is built for big moments, big drops, and public commitment to the bit.",
    accurateCopy: "Your aux privileges include turning a normal evening into logistics.",
    roastCopy: "You hear a buildup and immediately start behaving like the wristband is non-refundable.",
    bestFor: "Pre-games, dance floors, cardio, convincing everyone one more song is harmless.",
    dangerousAround: "Early mornings, sensible shoes, people with work tomorrow.",
    shareCaption: "Festival Menace is my SoundLife result. Planning accordingly.",
    colorTheme: { background: "#1C1230", accent: "#A3E635", text: "#F7FEE7" },
    emoji: "🎪",
    sticker: "💥",
  },
  {
    id: "lo-fi-ghost",
    name: "Lo-Fi Ghost",
    requiredTraits: ["softness", "focus", "darkness"],
    preferredScenarios: ["focus", "chill", "sad"],
    preferredGenres: ["lo-fi", "instrumental", "jazz", "indie"],
    blockedGenres: ["metal", "techno"],
    preferredLanguages: ["instrumental", "english", "japanese"],
    diagnosis: "You haunt your own to-do list with excellent ambient texture.",
    softCopy: "Your taste wants gentle loops, muted edges, and room to think.",
    accurateCopy: "This result knows you can disappear for three hours and call it focus.",
    roastCopy: "You put on lo-fi and became a background character in your own apartment.",
    bestFor: "Study sessions, rainy rooms, quiet chores, pretending the deadline is friendly.",
    dangerousAround: "Beds, warm lamps, tasks that require urgency.",
    shareCaption: "Lo-Fi Ghost. Present in spirit, absent in replies.",
    colorTheme: { background: "#1E293B", accent: "#93C5FD", text: "#F8FAFC" },
    emoji: "📻",
    sticker: "👻",
  },
  {
    id: "pretty-toxic",
    name: "Pretty Toxic",
    requiredTraits: ["confidence", "romance", "chaos"],
    preferredScenarios: ["party", "sad", "drive", "random"],
    preferredGenres: ["r&b", "pop", "reggaeton", "hip-hop"],
    blockedGenres: ["folk"],
    preferredLanguages: ["english", "spanish", "korean"],
    diagnosis: "The melody is gorgeous. The decision-making is under review.",
    softCopy: "You like pretty songs with a bite and hooks that know they are trouble.",
    accurateCopy: "Do not play this around anyone you are pretending to be normal about.",
    roastCopy: "You call it taste, but the playlist is basically a red flag with harmonies.",
    bestFor: "Getting ready, late texts, dramatic exits, pretending not to enjoy the chaos.",
    dangerousAround: "Situationships, mirror selfies, songs with whispered ad-libs.",
    shareCaption: "Pretty Toxic. I accept the diagnosis.",
    colorTheme: { background: "#2C1027", accent: "#FB7185", text: "#FFF1F2" },
    emoji: "💅",
    sticker: "🚩",
  },
  {
    id: "main-stage-delusion",
    name: "Main Stage Delusion",
    requiredTraits: ["confidence", "energy", "cinematic"],
    preferredScenarios: ["party", "gym", "drive"],
    preferredGenres: ["pop", "edm", "k-pop", "hip-hop"],
    blockedGenres: ["lo-fi", "folk"],
    preferredLanguages: ["english", "korean", "spanish"],
    diagnosis: "You require choruses large enough to be seen from the back row.",
    softCopy: "Your taste likes shine, scale, and songs that make the moment feel announced.",
    accurateCopy: "We regret to inform you the imaginary crowd is absolutely cheering.",
    roastCopy: "You put on one anthem and started accepting awards in the kitchen.",
    bestFor: "Big entrances, gym PRs, dance breaks, walking like there are cameras.",
    dangerousAround: "Escalators, empty parking lots, any reflective surface.",
    shareCaption: "Main Stage Delusion. Crowd goes wild.",
    colorTheme: { background: "#111827", accent: "#FACC15", text: "#FFFBEB" },
    emoji: "🏟️",
    sticker: "🎤",
  },
  {
    id: "cowboy-trauma-recovery",
    name: "Cowboy Trauma Recovery",
    requiredTraits: ["warmth", "romance", "softness"],
    preferredScenarios: ["sad", "chill", "drive"],
    preferredGenres: ["country", "folk", "soul", "indie"],
    blockedGenres: ["metal", "techno"],
    preferredLanguages: ["english"],
    diagnosis: "You may reject the cowboy aesthetic, but you respect a chorus that knows heartbreak.",
    softCopy: "Your taste wants honest warmth, plainspoken feeling, and a little porch-light healing.",
    accurateCopy: "This is suspiciously accurate because you said no country, then kept the heartbreak receipt.",
    roastCopy: "You hate cowboy sadness until the bridge hits, then suddenly the horse has a point.",
    bestFor: "Late drives, healing eras, sunset walks, admitting the simple lyric did get you.",
    dangerousAround: "Porches, whiskey metaphors, people with acoustic guitars and unresolved feelings.",
    shareCaption: "Cowboy Trauma Recovery found the part of me with a porch.",
    colorTheme: { background: "#2B1D12", accent: "#C08457", text: "#FFF7ED" },
    emoji: "🤠",
    sticker: "🥃",
  },
  {
    id: "bass-more-than-lyrics",
    name: "Bass More Than Lyrics",
    requiredTraits: ["confidence", "energy", "chaos"],
    preferredScenarios: ["gym", "party", "drive"],
    preferredGenres: ["hip-hop", "edm", "reggaeton", "amapiano", "afrobeats"],
    blockedGenres: ["classical", "folk", "acoustic"],
    preferredLanguages: ["english", "spanish", "instrumental"],
    diagnosis: "You do not need to know every word when the low end is doing legal damage.",
    softCopy: "Your taste follows impact, pulse, and physical proof that the speaker is alive.",
    accurateCopy: "Your aux privileges include prioritizing chest pressure over lyrical analysis.",
    roastCopy: "You heard the bass and said comprehension is optional.",
    bestFor: "Gym sets, car rides, parties, testing whether a speaker has self-respect.",
    dangerousAround: "Tiny Bluetooth speakers, downstairs neighbors, people explaining lyrics.",
    shareCaption: "Bass More Than Lyrics. I stand by it.",
    colorTheme: { background: "#0F172A", accent: "#22C55E", text: "#F0FDF4" },
    emoji: "🔊",
    sticker: "💣",
  },
  {
    id: "coffee-shop-dramatic",
    name: "Coffee Shop Dramatic",
    requiredTraits: ["softness", "focus", "cinematic"],
    preferredScenarios: ["focus", "chill", "sad"],
    preferredGenres: ["jazz", "lo-fi", "indie", "r&b"],
    blockedGenres: ["metal", "edm"],
    preferredLanguages: ["english", "french", "instrumental"],
    diagnosis: "You want productivity, but make it look like a critically acclaimed third place.",
    softCopy: "Your taste likes focus music with warmth, texture, and a little romantic lighting.",
    accurateCopy: "This result knows you can make one iced coffee feel like a character arc.",
    roastCopy: "You opened a laptop and started acting like the espresso machine was scoring your memoir.",
    bestFor: "Deep work, journaling, expensive pastries, reading the same paragraph with feeling.",
    dangerousAround: "Window seats, cute baristas, unread emails, tiny tables.",
    shareCaption: "Coffee Shop Dramatic. My laptop has lore.",
    colorTheme: { background: "#2A1B12", accent: "#C08457", text: "#FFF7ED" },
    emoji: "☕",
    sticker: "📓",
  },
  {
    id: "pre-workout-prophet",
    name: "Pre-Workout Prophet",
    requiredTraits: ["aggression", "energy", "tempo"],
    preferredScenarios: ["gym"],
    preferredGenres: ["hip-hop", "metal", "edm", "techno"],
    blockedGenres: ["lo-fi", "acoustic"],
    preferredLanguages: ["english", "instrumental"],
    diagnosis: "The caffeine entered your bloodstream and started giving motivational speeches.",
    softCopy: "Your taste wants speed, force, and zero emotional hesitation.",
    accurateCopy: "Do not play this around anyone who thinks a warmup should be peaceful.",
    roastCopy: "You took one scoop and began negotiating with gravity like it owed you money.",
    bestFor: "Heavy sets, hill sprints, cleaning like you have a deadline and an enemy.",
    dangerousAround: "Rest days, calm playlists, anyone eating a protein bar quietly.",
    shareCaption: "Pre-Workout Prophet has spoken.",
    colorTheme: { background: "#1C0F0A", accent: "#F97316", text: "#FFF7ED" },
    emoji: "⚡",
    sticker: "🏋️",
  },
  {
    id: "songs-in-languages-you-dont-speak",
    name: "Songs In Languages You Don't Speak",
    requiredTraits: ["warmth", "romance", "cinematic"],
    preferredScenarios: ["drive", "chill", "party", "sad", "random"],
    preferredGenres: ["k-pop", "j-pop", "latin-pop", "bollywood", "thai-pop", "afrobeats"],
    blockedGenres: [],
    preferredLanguages: ["japanese", "korean", "spanish", "hindi", "thai", "punjabi", "french", "arabic", "portuguese"],
    diagnosis: "You trust the melody before the translation and somehow keep being right.",
    softCopy: "Your taste is global, curious, and very willing to catch feelings phonetically.",
    accurateCopy: "This is suspiciously accurate because you do not need the words to know the chorus is guilty.",
    roastCopy: "You cannot pronounce the title, but you have already assigned it to three life events.",
    bestFor: "Discovery spirals, global playlists, language filters, dancing first and Googling later.",
    dangerousAround: "Translation tabs, karaoke nights, friends asking what does this mean.",
    shareCaption: "My SoundLife says subtitles are optional.",
    colorTheme: { background: "#122B2A", accent: "#2DD4BF", text: "#F0FDFA" },
    emoji: "🌐",
    sticker: "🗣️",
  },
  {
    id: "skip-intro-sprinter",
    name: "Skip Intro Sprinter",
    requiredTraits: ["tempo", "focus", "energy"],
    preferredScenarios: ["gym", "drive", "focus", "party"],
    preferredGenres: ["edm", "hip-hop", "pop", "k-pop", "reggaeton"],
    blockedGenres: ["classical", "folk", "acoustic"],
    preferredLanguages: ["english", "korean", "spanish", "instrumental"],
    diagnosis: "Your patience ends at second seven. The song needs to arrive already.",
    softCopy: "Your taste prefers momentum, clean starts, and no wandering around the point.",
    accurateCopy: "You are legally required to skip slow intros unless the payoff is historic.",
    roastCopy: "You gave a song six seconds and acted like you completed peer review.",
    bestFor: "Sprints, deadlines, short drives, playlists that do not ask for trust falls.",
    dangerousAround: "Albums with interludes, ambient builds, friends who say wait for the drop.",
    shareCaption: "Skip Intro Sprinter. Get to the chorus.",
    colorTheme: { background: "#102015", accent: "#22C55E", text: "#F0FDF4" },
    emoji: "⏭️",
    sticker: "🏃",
  },
];
