import type { Catalog, Scenario, Song, VibeCardData } from "./types";

/**
 * Curated local catalog. The app runs entirely on this when Supabase is
 * unconfigured or unreachable; when a newer remote catalog exists it is
 * merged over this set (remote rows win on title+artist / id).
 *
 * Platform URLs are intentionally left empty — lib/platforms.ts builds
 * search deep links so we never ship made-up track IDs.
 */

export const FALLBACK_CATALOG_VERSION = 1;

export const FALLBACK_VIBE_CARDS: VibeCardData[] = [
  {
    id: "late-night-highway",
    emoji: "🌙",
    title: "Late-night highway",
    subtitle: "Empty roads, heavy thoughts",
    traits: { darkness: 2, cinematic: 2, focus: 1 },
    feedback: "+ Dark",
  },
  {
    id: "spicy-food",
    emoji: "🌶️",
    title: "Spicy food",
    subtitle: "You like intensity",
    traits: { energy: 2, aggression: 1, chaos: 1 },
    feedback: "+ Intensity",
  },
  {
    id: "boxing",
    emoji: "🥊",
    title: "Boxing",
    subtitle: "Focused aggression",
    traits: { aggression: 2, energy: 2, focus: 1 },
    feedback: "+ Aggression",
  },
  {
    id: "coffee-shop",
    emoji: "☕",
    title: "Coffee shop",
    subtitle: "Soft focus mode",
    traits: { softness: 2, focus: 2, warmth: 1 },
    feedback: "+ Soft",
  },
  {
    id: "rainy-days",
    emoji: "🌧️",
    title: "Rainy days",
    subtitle: "Melancholy but cozy",
    traits: { darkness: 1, softness: 2, romance: 1 },
    feedback: "+ Melancholy",
  },
  {
    id: "beach-sunset",
    emoji: "🏖️",
    title: "Beach sunset",
    subtitle: "Warm, open, relaxed",
    traits: { warmth: 2, softness: 1, romance: 1 },
    feedback: "+ Warmth",
  },
  {
    id: "restless-energy",
    emoji: "⚡",
    title: "Restless energy",
    subtitle: "You need motion",
    traits: { energy: 2, tempo: 2, chaos: 1 },
    feedback: "+ Energy",
  },
  {
    id: "dark-rooms",
    emoji: "🖤",
    title: "Dark rooms",
    subtitle: "Moody and cinematic",
    traits: { darkness: 2, cinematic: 2 },
    feedback: "+ Cinematic",
  },
  {
    id: "dance-floor",
    emoji: "🕺",
    title: "Dance floor",
    subtitle: "You want movement",
    traits: { tempo: 2, energy: 2, confidence: 1 },
    feedback: "+ Movement",
  },
  {
    id: "deep-work",
    emoji: "🧠",
    title: "Deep work",
    subtitle: "No lyrics, just flow",
    traits: { focus: 2, tempo: 1 },
    feedback: "+ Focus",
  },
  {
    id: "main-character",
    emoji: "🔥",
    title: "Main character",
    subtitle: "You want drama",
    traits: { cinematic: 2, confidence: 2 },
    feedback: "+ Drama",
  },
  {
    id: "rage-cleaning",
    emoji: "🧹",
    title: "Rage cleaning",
    subtitle: "Productive chaos",
    traits: { chaos: 2, energy: 1, aggression: 1 },
    feedback: "+ Chaos",
  },
  {
    id: "heartbreak-montage",
    emoji: "💔",
    title: "Heartbreak montage",
    subtitle: "Sad but beautiful",
    traits: { romance: 2, darkness: 1, cinematic: 1 },
    feedback: "+ Feels",
  },
  {
    id: "feeling-expensive",
    emoji: "🤑",
    title: "Feeling expensive",
    subtitle: "Luxury confidence",
    traits: { confidence: 2, cinematic: 1 },
    feedback: "+ Luxury",
  },
  {
    id: "road-trip",
    emoji: "🛣️",
    title: "Road trip",
    subtitle: "Forward motion",
    traits: { tempo: 1, warmth: 1, energy: 1, cinematic: 1 },
    feedback: "+ Motion",
  },
  {
    id: "walking-fast",
    emoji: "😤",
    title: "Walking fast, ignoring texts",
    subtitle: "Places to be, peace to keep",
    traits: { tempo: 2, confidence: 1, focus: 1 },
    feedback: "+ Momentum",
  },
];

export const FALLBACK_SCENARIOS: Scenario[] = [
  {
    id: "drive",
    emoji: "🚗",
    label: "Drive",
    tagline: "Windows down or midnight run",
    baseTraits: { cinematic: 2, tempo: 1, energy: 1 },
    deck: [
      "late-night-highway",
      "road-trip",
      "dark-rooms",
      "main-character",
      "beach-sunset",
      "rainy-days",
      "restless-energy",
    ],
  },
  {
    id: "gym",
    emoji: "🏋️",
    label: "Gym",
    tagline: "Lift heavy, feel unstoppable",
    baseTraits: { energy: 2, aggression: 2, tempo: 1 },
    deck: [
      "boxing",
      "restless-energy",
      "main-character",
      "feeling-expensive",
      "spicy-food",
      "dark-rooms",
      "rage-cleaning",
    ],
  },
  {
    id: "focus",
    emoji: "💻",
    label: "Focus",
    tagline: "Lock in, tune out",
    baseTraits: { focus: 2, softness: 1 },
    deck: [
      "deep-work",
      "coffee-shop",
      "rainy-days",
      "dark-rooms",
      "walking-fast",
      "late-night-highway",
      "feeling-expensive",
    ],
  },
  {
    id: "party",
    emoji: "🎉",
    label: "Party",
    tagline: "Tonight has potential",
    baseTraits: { energy: 2, tempo: 2, chaos: 1 },
    deck: [
      "dance-floor",
      "spicy-food",
      "feeling-expensive",
      "main-character",
      "restless-energy",
      "beach-sunset",
      "dark-rooms",
    ],
  },
  {
    id: "sad",
    emoji: "😔",
    label: "Sad",
    tagline: "Feel it all the way through",
    baseTraits: { darkness: 1, softness: 1, romance: 1 },
    deck: [
      "heartbreak-montage",
      "rainy-days",
      "late-night-highway",
      "dark-rooms",
      "coffee-shop",
      "main-character",
      "beach-sunset",
    ],
  },
  {
    id: "chill",
    emoji: "😌",
    label: "Chill",
    tagline: "Low stakes, high vibes",
    baseTraits: { softness: 2, warmth: 2 },
    deck: [
      "beach-sunset",
      "coffee-shop",
      "rainy-days",
      "road-trip",
      "deep-work",
      "heartbreak-montage",
      "feeling-expensive",
    ],
  },
  {
    id: "random",
    emoji: "🎲",
    label: "Random Me",
    tagline: "Surprise me, I contain multitudes",
    baseTraits: {},
    deck: [],
  },
];

export const FALLBACK_SONGS: Song[] = [
  {
    id: "after-hours-the-weeknd",
    title: "After Hours",
    artist: "The Weeknd",
    language: "english",
    region: "north-america",
    genres: ["r&b", "pop"],
    era: "2020s",
    platforms: {},
    traits: { darkness: 3, cinematic: 2, energy: 2, tempo: 1 },
    scenarios: ["drive", "sad"],
    chips: [
      { emoji: "🌙", label: "Night drive" },
      { emoji: "🖤", label: "Dark" },
      { emoji: "⚡", label: "High energy" },
    ],
    popularity: 90,
  },
  {
    id: "humble-kendrick-lamar",
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, aggression: 2, energy: 2 },
    scenarios: ["gym", "party", "drive"],
    chips: [
      { emoji: "👑", label: "Confidence" },
      { emoji: "🥊", label: "Hard-hitting" },
    ],
    popularity: 92,
  },
  {
    id: "the-search-nf",
    title: "The Search",
    artist: "NF",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { aggression: 2, darkness: 2, energy: 2, focus: 1 },
    scenarios: ["gym", "drive"],
    chips: [
      { emoji: "🥊", label: "Aggression" },
      { emoji: "🧠", label: "Introspective" },
    ],
    popularity: 74,
  },
  {
    id: "pursuit-gesaffelstein",
    title: "Pursuit",
    artist: "Gesaffelstein",
    language: "instrumental",
    region: "europe",
    genres: ["edm", "techno"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 3, aggression: 2, cinematic: 2, tempo: 2 },
    scenarios: ["gym", "drive", "party"],
    chips: [
      { emoji: "🖤", label: "Dark techno" },
      { emoji: "🎬", label: "Cinematic" },
      { emoji: "⚡", label: "Relentless" },
    ],
    popularity: 70,
  },
  {
    id: "power-kanye-west",
    title: "POWER",
    artist: "Kanye West",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, energy: 3, aggression: 1 },
    scenarios: ["gym", "party"],
    chips: [
      { emoji: "👑", label: "Main character" },
      { emoji: "⚡", label: "Energy" },
    ],
    popularity: 90,
  },
  {
    id: "goosebumps-travis-scott",
    title: "goosebumps",
    artist: "Travis Scott",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 2, energy: 2, chaos: 1, tempo: 1 },
    scenarios: ["party", "drive", "gym"],
    chips: [
      { emoji: "🌙", label: "Late night" },
      { emoji: "🌪️", label: "Hypnotic" },
    ],
    popularity: 89,
  },
  {
    id: "good-days-sza",
    title: "Good Days",
    artist: "SZA",
    language: "english",
    region: "north-america",
    genres: ["r&b"],
    era: "2020s",
    platforms: {},
    traits: { softness: 3, warmth: 2, romance: 2 },
    scenarios: ["chill", "sad", "focus"],
    chips: [
      { emoji: "🪶", label: "Soft" },
      { emoji: "🌅", label: "Warm glow" },
    ],
    popularity: 87,
  },
  {
    id: "nights-frank-ocean",
    title: "Nights",
    artist: "Frank Ocean",
    language: "english",
    region: "north-america",
    genres: ["r&b"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, romance: 2, cinematic: 2, darkness: 1 },
    scenarios: ["sad", "chill", "drive"],
    chips: [
      { emoji: "💔", label: "Two moods" },
      { emoji: "🌙", label: "Late night" },
    ],
    popularity: 91,
  },
  {
    id: "bury-a-friend-billie-eilish",
    title: "bury a friend",
    artist: "Billie Eilish",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 3, chaos: 2, cinematic: 1 },
    scenarios: ["sad", "drive", "gym"],
    chips: [
      { emoji: "🖤", label: "Eerie" },
      { emoji: "🌪️", label: "Unhinged" },
    ],
    popularity: 84,
  },
  {
    id: "a-moment-apart-odesza",
    title: "A Moment Apart",
    artist: "ODESZA",
    language: "instrumental",
    region: "north-america",
    genres: ["edm"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 3, warmth: 2, energy: 1, focus: 1 },
    scenarios: ["focus", "chill", "drive"],
    chips: [
      { emoji: "🎬", label: "Cinematic" },
      { emoji: "🌅", label: "Euphoric" },
    ],
    popularity: 72,
  },
  {
    id: "passionfruit-drake",
    title: "Passionfruit",
    artist: "Drake",
    language: "english",
    region: "north-america",
    genres: ["pop", "r&b"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, warmth: 2, romance: 2, tempo: 1 },
    scenarios: ["chill", "party", "sad"],
    chips: [
      { emoji: "🏝️", label: "Tropical" },
      { emoji: "🪶", label: "Smooth" },
    ],
    popularity: 86,
  },
  {
    id: "superhero-metro-boomin",
    title: "Superhero (Heroes & Villains)",
    artist: "Metro Boomin",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { darkness: 2, confidence: 2, cinematic: 2 },
    scenarios: ["gym", "drive", "party"],
    chips: [
      { emoji: "🎬", label: "Villain arc" },
      { emoji: "🖤", label: "Dark" },
    ],
    popularity: 85,
  },
  {
    id: "see-you-again-tyler-the-creator",
    title: "See You Again",
    artist: "Tyler, The Creator",
    language: "english",
    region: "north-america",
    genres: ["r&b", "hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 3, softness: 2, warmth: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [
      { emoji: "💘", label: "Dreamy" },
      { emoji: "🪶", label: "Soft" },
    ],
    popularity: 88,
  },
  {
    id: "let-it-happen-tame-impala",
    title: "Let It Happen",
    artist: "Tame Impala",
    language: "english",
    region: "oceania",
    genres: ["indie", "rock"],
    era: "2010s",
    platforms: {},
    traits: { chaos: 2, cinematic: 2, energy: 2, tempo: 2, focus: 1 },
    scenarios: ["drive", "focus", "party"],
    chips: [
      { emoji: "🌪️", label: "Spiraling" },
      { emoji: "🎬", label: "Epic build" },
    ],
    popularity: 85,
  },
  {
    id: "circles-post-malone",
    title: "Circles",
    artist: "Post Malone",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, warmth: 1, romance: 1, darkness: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [
      { emoji: "🪶", label: "Easy" },
      { emoji: "💔", label: "Bittersweet" },
    ],
    popularity: 84,
  },
  {
    id: "physical-dua-lipa",
    title: "Physical",
    artist: "Dua Lipa",
    language: "english",
    region: "europe",
    genres: ["pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 3, tempo: 3, confidence: 2 },
    scenarios: ["party", "gym"],
    chips: [
      { emoji: "⚡", label: "Cardio" },
      { emoji: "🕺", label: "Movement" },
    ],
    popularity: 82,
  },
  {
    id: "delilah-fred-again",
    title: "Delilah (pull me out of this)",
    artist: "Fred again..",
    language: "english",
    region: "europe",
    genres: ["edm"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, romance: 1, chaos: 1, focus: 1 },
    scenarios: ["party", "focus", "drive"],
    chips: [
      { emoji: "🕺", label: "Late-night dance" },
      { emoji: "💘", label: "Emotional" },
    ],
    popularity: 83,
  },
  {
    id: "redbone-childish-gambino",
    title: "Redbone",
    artist: "Childish Gambino",
    language: "english",
    region: "north-america",
    genres: ["r&b", "funk"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 2, romance: 2, softness: 2, darkness: 1 },
    scenarios: ["chill", "sad"],
    chips: [
      { emoji: "🌅", label: "Groove" },
      { emoji: "💘", label: "Smooth" },
    ],
    popularity: 88,
  },
  {
    id: "do-i-wanna-know-arctic-monkeys",
    title: "Do I Wanna Know?",
    artist: "Arctic Monkeys",
    language: "english",
    region: "europe",
    genres: ["rock", "indie"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 2, romance: 2, confidence: 1, cinematic: 1 },
    scenarios: ["drive", "sad", "gym"],
    chips: [
      { emoji: "🖤", label: "Brooding" },
      { emoji: "💘", label: "Tension" },
    ],
    popularity: 90,
  },
  {
    id: "glimpse-of-us-joji",
    title: "Glimpse of Us",
    artist: "Joji",
    language: "english",
    region: "north-america",
    genres: ["pop", "lo-fi"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, softness: 3, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [
      { emoji: "💔", label: "Heartbreak" },
      { emoji: "🪶", label: "Fragile" },
    ],
    popularity: 85,
  },
  {
    id: "midnight-city-m83",
    title: "Midnight City",
    artist: "M83",
    language: "english",
    region: "europe",
    genres: ["edm", "indie"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 3, energy: 2, tempo: 2, warmth: 1 },
    scenarios: ["drive", "party", "focus"],
    chips: [
      { emoji: "🌃", label: "City lights" },
      { emoji: "🎬", label: "Movie ending" },
    ],
    popularity: 86,
  },
  {
    id: "instant-crush-daft-punk",
    title: "Instant Crush",
    artist: "Daft Punk",
    language: "english",
    region: "europe",
    genres: ["edm", "pop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 2, cinematic: 1, softness: 1, tempo: 1, warmth: 1 },
    scenarios: ["drive", "chill", "sad"],
    chips: [
      { emoji: "💘", label: "Wistful" },
      { emoji: "🌃", label: "Synth glow" },
    ],
    popularity: 84,
  },
  {
    id: "no-role-modelz-j-cole",
    title: "No Role Modelz",
    artist: "J. Cole",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 2, warmth: 1, focus: 1, tempo: 1 },
    scenarios: ["chill", "drive", "party"],
    chips: [
      { emoji: "👑", label: "Self-made" },
      { emoji: "🌅", label: "Laid-back" },
    ],
    popularity: 88,
  },
  {
    id: "needed-me-rihanna",
    title: "Needed Me",
    artist: "Rihanna",
    language: "english",
    region: "caribbean",
    genres: ["r&b", "pop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, darkness: 2, softness: 1 },
    scenarios: ["party", "drive", "gym"],
    chips: [
      { emoji: "👑", label: "Savage" },
      { emoji: "🖤", label: "Cold" },
    ],
    popularity: 85,
  },
  {
    id: "feel-so-close-calvin-harris",
    title: "Feel So Close",
    artist: "Calvin Harris",
    language: "english",
    region: "europe",
    genres: ["edm"],
    era: "2010s",
    platforms: {},
    traits: { energy: 2, warmth: 2, tempo: 2, romance: 1 },
    scenarios: ["party", "gym", "drive"],
    chips: [
      { emoji: "⚡", label: "Festival" },
      { emoji: "🌅", label: "Feel-good" },
    ],
    popularity: 80,
  },
  {
    id: "awake-tycho",
    title: "Awake",
    artist: "Tycho",
    language: "instrumental",
    region: "north-america",
    genres: ["electronic", "lo-fi"],
    era: "2010s",
    platforms: {},
    traits: { focus: 3, warmth: 2, softness: 2 },
    scenarios: ["focus", "chill"],
    chips: [
      { emoji: "🧠", label: "Instrumental" },
      { emoji: "🌅", label: "Glow" },
    ],
    popularity: 65,
  },
  {
    id: "kerala-bonobo",
    title: "Kerala",
    artist: "Bonobo",
    language: "instrumental",
    region: "europe",
    genres: ["electronic"],
    era: "2010s",
    platforms: {},
    traits: { focus: 3, tempo: 1, softness: 1, cinematic: 1 },
    scenarios: ["focus", "chill"],
    chips: [
      { emoji: "🧠", label: "Flow state" },
      { emoji: "🥁", label: "Pulse" },
    ],
    popularity: 68,
  },
  {
    id: "motion-sickness-phoebe-bridgers",
    title: "Motion Sickness",
    artist: "Phoebe Bridgers",
    language: "english",
    region: "north-america",
    genres: ["indie"],
    era: "2010s",
    platforms: {},
    traits: { romance: 2, softness: 2, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [
      { emoji: "💔", label: "Bittersweet" },
      { emoji: "🌧️", label: "Indie ache" },
    ],
    popularity: 75,
  },
  {
    id: "holocene-bon-iver",
    title: "Holocene",
    artist: "Bon Iver",
    language: "english",
    region: "north-america",
    genres: ["indie", "folk"],
    era: "2010s",
    platforms: {},
    traits: { softness: 3, cinematic: 2, warmth: 1, romance: 1 },
    scenarios: ["sad", "chill", "focus"],
    chips: [
      { emoji: "🌧️", label: "Quiet awe" },
      { emoji: "🎬", label: "Wide open" },
    ],
    popularity: 80,
  },
  {
    id: "latch-disclosure",
    title: "Latch",
    artist: "Disclosure",
    language: "english",
    region: "europe",
    genres: ["edm"],
    era: "2010s",
    platforms: {},
    traits: { energy: 2, romance: 2, tempo: 2, warmth: 1 },
    scenarios: ["party", "gym"],
    chips: [
      { emoji: "🕺", label: "Dance" },
      { emoji: "💘", label: "Euphoric" },
    ],
    popularity: 81,
  },
  {
    id: "till-i-collapse-eminem",
    title: "Till I Collapse",
    artist: "Eminem",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2000s",
    platforms: {},
    traits: { aggression: 3, energy: 3, confidence: 2 },
    scenarios: ["gym"],
    chips: [
      { emoji: "🥊", label: "Last rep" },
      { emoji: "⚡", label: "Relentless" },
    ],
    popularity: 90,
  },
  {
    id: "day-n-nite-kid-cudi",
    title: "Day 'N' Nite",
    artist: "Kid Cudi",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2000s",
    platforms: {},
    traits: { darkness: 2, focus: 1, softness: 1, cinematic: 1 },
    scenarios: ["drive", "sad", "focus"],
    chips: [
      { emoji: "🌙", label: "Night loner" },
      { emoji: "🖤", label: "Moody" },
    ],
    popularity: 82,
  },
  {
    id: "summertime-sadness-lana-del-rey",
    title: "Summertime Sadness",
    artist: "Lana Del Rey",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 2, romance: 2, darkness: 2, warmth: 1 },
    scenarios: ["sad", "drive", "chill"],
    chips: [
      { emoji: "🎬", label: "Tragic glam" },
      { emoji: "💔", label: "Summer ache" },
    ],
    popularity: 86,
  },
  {
    id: "uptown-funk-mark-ronson",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    language: "english",
    region: "north-america",
    genres: ["pop", "funk"],
    era: "2010s",
    platforms: {},
    traits: { energy: 3, tempo: 3, confidence: 2, warmth: 1 },
    scenarios: ["party"],
    chips: [
      { emoji: "🕺", label: "Instant party" },
      { emoji: "👑", label: "Swagger" },
    ],
    popularity: 87,
  },

  /* ----------------------------- global ----------------------------- */

  {
    id: "titi-me-pregunto-bad-bunny",
    title: "Tití Me Preguntó",
    artist: "Bad Bunny",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, confidence: 2, chaos: 1 },
    scenarios: ["party", "gym", "drive"],
    chips: [
      { emoji: "🔥", label: "Global heat" },
      { emoji: "🕺", label: "Perreo" },
    ],
    popularity: 92,
  },
  {
    id: "despecha-rosalia",
    title: "DESPECHÁ",
    artist: "ROSALÍA",
    language: "spanish",
    region: "europe",
    genres: ["pop", "reggaeton"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 2, warmth: 2, confidence: 1 },
    scenarios: ["party", "chill"],
    chips: [
      { emoji: "☀️", label: "Summer strut" },
      { emoji: "🕺", label: "Light feet" },
    ],
    popularity: 84,
  },
  {
    id: "mi-gente-j-balvin",
    title: "Mi Gente",
    artist: "J Balvin & Willy William",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton", "edm"],
    era: "2010s",
    platforms: {},
    traits: { energy: 3, tempo: 2, chaos: 1 },
    scenarios: ["party"],
    chips: [
      { emoji: "🎉", label: "Instant party" },
      { emoji: "🌎", label: "Borderless" },
    ],
    popularity: 85,
  },
  {
    id: "provenza-karol-g",
    title: "PROVENZA",
    artist: "KAROL G",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton", "pop"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, softness: 2, tempo: 1, romance: 1 },
    scenarios: ["chill", "party"],
    chips: [
      { emoji: "🏝️", label: "Beach pace" },
      { emoji: "🌅", label: "Easy glow" },
    ],
    popularity: 86,
  },
  {
    id: "super-shy-newjeans",
    title: "Super Shy",
    artist: "NewJeans",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 2, softness: 2, romance: 1, energy: 1 },
    scenarios: ["party", "chill", "focus"],
    chips: [
      { emoji: "🫧", label: "Featherlight" },
      { emoji: "🕺", label: "Skip-walk" },
    ],
    popularity: 87,
  },
  {
    id: "ddu-du-ddu-du-blackpink",
    title: "DDU-DU DDU-DU",
    artist: "BLACKPINK",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, energy: 2, aggression: 1 },
    scenarios: ["gym", "party"],
    chips: [
      { emoji: "👑", label: "Boss walk" },
      { emoji: "🥊", label: "Swagger" },
    ],
    popularity: 88,
  },
  {
    id: "supernova-aespa",
    title: "Supernova",
    artist: "aespa",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, chaos: 1, confidence: 1 },
    scenarios: ["party", "gym"],
    chips: [
      { emoji: "⚡", label: "Hyper" },
      { emoji: "🌪️", label: "Glitch-pop" },
    ],
    popularity: 84,
  },
  {
    id: "spring-day-bts",
    title: "Spring Day",
    artist: "BTS",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, romance: 2, cinematic: 2, warmth: 1 },
    scenarios: ["sad", "chill"],
    chips: [
      { emoji: "💔", label: "Missing someone" },
      { emoji: "🎬", label: "Wide shot" },
    ],
    popularity: 89,
  },
  {
    id: "idol-yoasobi",
    title: "アイドル (Idol)",
    artist: "YOASOBI",
    language: "japanese",
    region: "japan",
    genres: ["j-pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, chaos: 2, cinematic: 1 },
    scenarios: ["party", "focus"],
    chips: [
      { emoji: "⚡", label: "Hyper-pop rush" },
      { emoji: "🎬", label: "Anime opening" },
    ],
    popularity: 88,
  },
  {
    id: "shinunoga-e-wa-fujii-kaze",
    title: "Shinunoga E-Wa",
    artist: "Fujii Kaze",
    language: "japanese",
    region: "japan",
    genres: ["j-pop", "r&b"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, softness: 2, warmth: 1 },
    scenarios: ["chill", "sad"],
    chips: [
      { emoji: "💘", label: "Devotion" },
      { emoji: "🪶", label: "Smooth" },
    ],
    popularity: 85,
  },
  {
    id: "kick-back-kenshi-yonezu",
    title: "KICK BACK",
    artist: "Kenshi Yonezu",
    language: "japanese",
    region: "japan",
    genres: ["j-pop", "rock"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, chaos: 2, aggression: 2 },
    scenarios: ["gym", "party"],
    chips: [
      { emoji: "🌪️", label: "Unhinged" },
      { emoji: "🥊", label: "Power-up" },
    ],
    popularity: 84,
  },
  {
    id: "kesariya-arijit-singh",
    title: "Kesariya",
    artist: "Arijit Singh",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, warmth: 2, softness: 1, cinematic: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [
      { emoji: "💘", label: "Golden romance" },
      { emoji: "🎬", label: "Film moment" },
    ],
    popularity: 90,
  },
  {
    id: "jhoome-jo-pathaan-arijit-singh",
    title: "Jhoome Jo Pathaan",
    artist: "Arijit Singh & Vishal-Sheykhar",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, confidence: 1, cinematic: 1 },
    scenarios: ["party"],
    chips: [
      { emoji: "🎉", label: "Blockbuster" },
      { emoji: "🕺", label: "Full send" },
    ],
    popularity: 82,
  },
  {
    id: "brown-munde-ap-dhillon",
    title: "Brown Munde",
    artist: "AP Dhillon",
    language: "punjabi",
    region: "south-asia",
    genres: ["punjabi", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 2, darkness: 1, energy: 1, cinematic: 1 },
    scenarios: ["gym", "drive"],
    chips: [
      { emoji: "👑", label: "Quiet flex" },
      { emoji: "🌙", label: "Late roll" },
    ],
    popularity: 86,
  },
  {
    id: "295-sidhu-moose-wala",
    title: "295",
    artist: "Sidhu Moose Wala",
    language: "punjabi",
    region: "south-asia",
    genres: ["punjabi", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { darkness: 2, confidence: 2, cinematic: 1 },
    scenarios: ["drive", "gym"],
    chips: [
      { emoji: "🖤", label: "Heavy legacy" },
      { emoji: "👑", label: "Defiant" },
    ],
    popularity: 87,
  },
  {
    id: "last-last-burna-boy",
    title: "Last Last",
    artist: "Burna Boy",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, romance: 1, darkness: 1, tempo: 1 },
    scenarios: ["chill", "sad", "party"],
    chips: [
      { emoji: "💔", label: "Dancing through it" },
      { emoji: "🌍", label: "Lagos everywhere" },
    ],
    popularity: 88,
  },
  {
    id: "calm-down-rema",
    title: "Calm Down",
    artist: "Rema",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, romance: 2, tempo: 1 },
    scenarios: ["chill", "party"],
    chips: [
      { emoji: "🌅", label: "Sweet talk" },
      { emoji: "🕺", label: "Sway" },
    ],
    popularity: 89,
  },
  {
    id: "essence-wizkid",
    title: "Essence",
    artist: "Wizkid ft. Tems",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, softness: 2, romance: 2 },
    scenarios: ["chill"],
    chips: [
      { emoji: "🌅", label: "Honey-slow" },
      { emoji: "💘", label: "Smooth" },
    ],
    popularity: 88,
  },
  {
    id: "water-tyla",
    title: "Water",
    artist: "Tyla",
    language: "english",
    region: "south-africa",
    genres: ["amapiano", "pop"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 2, warmth: 2, romance: 1, confidence: 1 },
    scenarios: ["party", "chill"],
    chips: [
      { emoji: "💧", label: "Amapiano bounce" },
      { emoji: "🕺", label: "Hips first" },
    ],
    popularity: 87,
  },
  {
    id: "mnike-tyler-icu",
    title: "Mnike",
    artist: "Tyler ICU & Tumelo.za",
    language: "zulu",
    region: "south-africa",
    genres: ["amapiano"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 3, energy: 2, chaos: 1 },
    scenarios: ["party"],
    chips: [
      { emoji: "🥁", label: "Log drum" },
      { emoji: "🎉", label: "Ground-shake" },
    ],
    popularity: 80,
  },
  {
    id: "alors-on-danse-stromae",
    title: "Alors on danse",
    artist: "Stromae",
    language: "french",
    region: "europe",
    genres: ["pop", "edm"],
    era: "2010s",
    platforms: {},
    traits: { tempo: 2, energy: 2, darkness: 1 },
    scenarios: ["party", "sad"],
    chips: [
      { emoji: "🕺", label: "Dance anyway" },
      { emoji: "🖤", label: "Bittersweet" },
    ],
    popularity: 85,
  },
  {
    id: "djadja-aya-nakamura",
    title: "Djadja",
    artist: "Aya Nakamura",
    language: "french",
    region: "europe",
    genres: ["pop", "afrobeats"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 2, tempo: 2, warmth: 1 },
    scenarios: ["party", "chill"],
    chips: [
      { emoji: "👑", label: "Unbothered" },
      { emoji: "🕺", label: "Strut" },
    ],
    popularity: 83,
  },
  {
    id: "derniere-danse-indila",
    title: "Dernière Danse",
    artist: "Indila",
    language: "french",
    region: "europe",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 2, romance: 2, darkness: 1, softness: 1 },
    scenarios: ["sad", "drive"],
    chips: [
      { emoji: "🎬", label: "Rain-window opera" },
      { emoji: "💔", label: "One last dance" },
    ],
    popularity: 84,
  },
  {
    id: "tamally-maak-amr-diab",
    title: "Tamally Maak",
    artist: "Amr Diab",
    language: "arabic",
    region: "middle-east",
    genres: ["arab-pop"],
    era: "2000s",
    platforms: {},
    traits: { romance: 3, warmth: 2, softness: 1 },
    scenarios: ["chill", "sad"],
    chips: [
      { emoji: "💘", label: "Eternal" },
      { emoji: "🌅", label: "Mediterranean" },
    ],
    popularity: 85,
  },
  {
    id: "3-daqat-abu",
    title: "3 Daqat",
    artist: "Abu ft. Yousra",
    language: "arabic",
    region: "middle-east",
    genres: ["arab-pop"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 2, romance: 2, tempo: 1 },
    scenarios: ["chill", "party"],
    chips: [
      { emoji: "🌅", label: "Seaside" },
      { emoji: "💘", label: "Heartbeat" },
    ],
    popularity: 80,
  },
  {
    id: "vai-malandra-anitta",
    title: "Vai Malandra",
    artist: "Anitta",
    language: "portuguese",
    region: "brazil",
    genres: ["funk", "pop"],
    era: "2010s",
    platforms: {},
    traits: { energy: 2, tempo: 2, confidence: 2 },
    scenarios: ["party", "gym"],
    chips: [
      { emoji: "🎉", label: "Baile funk" },
      { emoji: "👑", label: "Carioca confidence" },
    ],
    popularity: 82,
  },
  {
    id: "sossego-tim-maia",
    title: "Sossego",
    artist: "Tim Maia",
    language: "portuguese",
    region: "brazil",
    genres: ["funk", "soul"],
    era: "1970s",
    platforms: {},
    traits: { warmth: 3, tempo: 1, softness: 1 },
    scenarios: ["chill"],
    chips: [
      { emoji: "🌅", label: "Sunday groove" },
      { emoji: "🕺", label: "Easy funk" },
    ],
    popularity: 78,
  },
  {
    id: "sudpang-milli",
    title: "สุดปัง (Sudpang!)",
    artist: "MILLI",
    language: "thai",
    region: "thailand",
    genres: ["thai-pop", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 2, energy: 2, chaos: 1, tempo: 1 },
    scenarios: ["party", "gym"],
    chips: [
      { emoji: "👑", label: "Bangkok flex" },
      { emoji: "🌶️", label: "Spice" },
    ],
    popularity: 75,
  },
  {
    id: "glad-ink-waruntorn",
    title: "ดีใจด้วยนะ (Glad)",
    artist: "INK WARUNTORN",
    language: "thai",
    region: "thailand",
    genres: ["thai-pop"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, romance: 2, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [
      { emoji: "💔", label: "Happy for you (not)" },
      { emoji: "🪶", label: "Gentle ache" },
    ],
    popularity: 76,
  },
  {
    id: "lover-boy-phum-viphurit",
    title: "Lover Boy",
    artist: "Phum Viphurit",
    language: "english",
    region: "thailand",
    genres: ["indie"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 2, softness: 1, romance: 1 },
    scenarios: ["chill"],
    chips: [
      { emoji: "🌅", label: "Sunshine indie" },
      { emoji: "🛵", label: "Breezy" },
    ],
    popularity: 74,
  },
  {
    id: "master-of-puppets-metallica",
    title: "Master of Puppets",
    artist: "Metallica",
    language: "english",
    region: "north-america",
    genres: ["metal"],
    era: "1980s",
    platforms: {},
    traits: { aggression: 3, energy: 3, darkness: 1, tempo: 1 },
    scenarios: ["gym"],
    chips: [
      { emoji: "🥊", label: "Riff cardio" },
      { emoji: "⚡", label: "Full throttle" },
    ],
    popularity: 88,
  },
  {
    id: "tennessee-whiskey-chris-stapleton",
    title: "Tennessee Whiskey",
    artist: "Chris Stapleton",
    language: "english",
    region: "north-america",
    genres: ["country", "soul"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 3, romance: 2, softness: 1 },
    scenarios: ["chill", "sad"],
    chips: [
      { emoji: "🥃", label: "Slow burn" },
      { emoji: "🌅", label: "Porch light" },
    ],
    popularity: 84,
  },
  {
    id: "take-five-dave-brubeck",
    title: "Take Five",
    artist: "Dave Brubeck",
    language: "instrumental",
    region: "north-america",
    genres: ["jazz"],
    era: "1950s",
    platforms: {},
    traits: { focus: 3, softness: 1, cinematic: 1 },
    scenarios: ["focus", "chill"],
    chips: [
      { emoji: "🧠", label: "5/4 flow" },
      { emoji: "🎷", label: "Timeless" },
    ],
    popularity: 80,
  },
  {
    id: "death-bed-powfu",
    title: "death bed (coffee for your head)",
    artist: "Powfu",
    language: "english",
    region: "north-america",
    genres: ["lo-fi", "pop"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 1, darkness: 1, focus: 1 },
    scenarios: ["sad", "chill", "focus"],
    chips: [
      { emoji: "🪶", label: "Bedroom lo-fi" },
      { emoji: "💔", label: "Soft sad" },
    ],
    popularity: 78,
  },
];

export const FALLBACK_CATALOG: Catalog = {
  version: FALLBACK_CATALOG_VERSION,
  songs: FALLBACK_SONGS,
  vibeCards: FALLBACK_VIBE_CARDS,
  scenarios: FALLBACK_SCENARIOS,
};
