import type { Catalog, Scenario, Song, VibeCardData } from "./types";

export const FALLBACK_CATALOG_VERSION = 2;

/* ================================================================== */
/* VIBE CARDS                                                          */
/* ================================================================== */

export const FALLBACK_VIBE_CARDS: VibeCardData[] = [
  /* ── Lifestyle ── */
  {
    id: "late-night-highway",
    emoji: "🌙",
    title: "Late-night highway",
    subtitle: "Empty roads, heavy thoughts",
    traits: { darkness: 2, cinematic: 2, focus: 1 },
    feedback: "+ Dark",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #1e1b4b, #312e81)",
    whyText: "You like music that matches the weight of 3am drives.",
  },
  {
    id: "coffee-shop",
    emoji: "☕",
    title: "Coffee shop",
    subtitle: "Soft focus mode",
    traits: { softness: 2, focus: 2, warmth: 1 },
    feedback: "+ Soft focus",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #fef3c7, #fde68a)",
    whyText: "You vibe with music that makes a coffee shop feel cinematic.",
  },
  {
    id: "rainy-days",
    emoji: "🌧️",
    title: "Rainy days",
    subtitle: "Melancholy but cozy",
    traits: { darkness: 1, softness: 2, romance: 1 },
    feedback: "+ Melancholy",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #dbeafe, #bfdbfe)",
    whyText: "Rain-window music. The kind that makes sadness feel intentional.",
  },
  {
    id: "beach-sunset",
    emoji: "🏖️",
    title: "Beach sunset",
    subtitle: "Warm, open, relaxed",
    traits: { warmth: 2, softness: 1, romance: 1 },
    feedback: "+ Warmth",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #fef3c7, #fed7aa)",
    whyText: "Golden hour. The music that makes you feel like you're there.",
  },
  {
    id: "restless-energy",
    emoji: "⚡",
    title: "Restless energy",
    subtitle: "You need motion",
    traits: { energy: 2, tempo: 2, chaos: 1 },
    feedback: "+ Energy",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fef08a, #fde047)",
    whyText: "You can't sit still. The music should match.",
  },
  {
    id: "dark-rooms",
    emoji: "🖤",
    title: "Dark rooms",
    subtitle: "Moody and cinematic",
    traits: { darkness: 2, cinematic: 2 },
    feedback: "+ Cinematic dark",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #3b0764, #4c1d95)",
    whyText: "Low light, high feeling. The kind of music rooms deserve.",
  },
  {
    id: "dance-floor",
    emoji: "🕺",
    title: "Dance floor",
    subtitle: "You want movement",
    traits: { tempo: 2, energy: 2, confidence: 1 },
    feedback: "+ Movement",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #fce7f3, #fbcfe8)",
    whyText: "You're not listening to music. You're becoming music.",
  },
  {
    id: "deep-work",
    emoji: "🧠",
    title: "Deep work",
    subtitle: "No lyrics, just flow",
    traits: { focus: 2, tempo: 1 },
    feedback: "+ Focus",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #d1fae5, #a7f3d0)",
    whyText: "Lyrics are a distraction. You need pure sonic architecture.",
    boostGenres: ["instrumental", "lo-fi", "electronic"],
  },
  {
    id: "main-character",
    emoji: "🔥",
    title: "Main character",
    subtitle: "You want drama",
    traits: { cinematic: 2, confidence: 2 },
    feedback: "+ Drama",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #ffe4e6, #fecdd3)",
    whyText: "The world is your montage. You need the soundtrack to match.",
  },
  {
    id: "rage-cleaning",
    emoji: "🧹",
    title: "Rage cleaning",
    subtitle: "Productive chaos",
    traits: { chaos: 2, energy: 1, aggression: 1 },
    feedback: "+ Chaos",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fee2e2, #fecaca)",
    whyText: "You're not angry. You're efficiently angry. Big difference.",
  },
  {
    id: "heartbreak-montage",
    emoji: "💔",
    title: "Heartbreak montage",
    subtitle: "Sad but beautiful",
    traits: { romance: 2, darkness: 1, cinematic: 1 },
    feedback: "+ Feels",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fce7f3, #f9a8d4)",
    whyText: "The feelings are real. The cinematography is excellent.",
  },
  {
    id: "feeling-expensive",
    emoji: "🤑",
    title: "Feeling expensive",
    subtitle: "Luxury confidence",
    traits: { confidence: 2, cinematic: 1 },
    feedback: "+ Luxury",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fef9c3, #fef08a)",
    whyText: "Champagne taste, golden sound.",
  },
  {
    id: "road-trip",
    emoji: "🛣️",
    title: "Road trip",
    subtitle: "Forward motion",
    traits: { tempo: 1, warmth: 1, energy: 1, cinematic: 1 },
    feedback: "+ Motion",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #dcfce7, #bbf7d0)",
    whyText: "Destination: vibe. ETA: whenever.",
  },
  {
    id: "walking-fast",
    emoji: "😤",
    title: "Walking fast, ignoring texts",
    subtitle: "Places to be, peace to keep",
    traits: { tempo: 2, confidence: 1, focus: 1 },
    feedback: "+ Momentum",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #e0e7ff, #c7d2fe)",
    whyText: "The sidewalk is a runway. You're always on time to somewhere.",
  },
  {
    id: "spicy-food",
    emoji: "🌶️",
    title: "Spicy food",
    subtitle: "You like intensity",
    traits: { energy: 2, aggression: 1, chaos: 1 },
    feedback: "+ Intensity",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fee2e2, #ef4444)",
    whyText: "Mild is boring. You choose the extra heat, every time.",
  },
  {
    id: "boxing",
    emoji: "🥊",
    title: "Boxing",
    subtitle: "Focused aggression",
    traits: { aggression: 2, energy: 2, focus: 1 },
    feedback: "+ Aggression",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #fee2e2, #fca5a5)",
    whyText: "The gym is a theatre. The gloves are props. You're the villain.",
  },

  /* ── Sound texture ── */
  {
    id: "heavy-bass",
    emoji: "🔊",
    title: "Heavy bass",
    subtitle: "Feel it in your chest",
    traits: { energy: 2, confidence: 1, chaos: 1 },
    feedback: "+ Bass",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #1e1b4b, #4c1d95)",
    whyText: "You measure music in chest pounds, not decibels.",
    boostGenres: ["hip-hop", "edm", "afrobeats", "amapiano", "reggaeton"],
  },
  {
    id: "fast-drums",
    emoji: "🥁",
    title: "Fast drums",
    subtitle: "Rhythm first, everything else second",
    traits: { tempo: 3, energy: 2, aggression: 1 },
    feedback: "+ Tempo",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #dcfce7, #86efac)",
    whyText: "The snare hits first. Everything else is decoration.",
    boostGenres: ["edm", "metal", "hip-hop", "amapiano"],
  },
  {
    id: "piano-only",
    emoji: "🎹",
    title: "Piano only",
    subtitle: "One instrument, everything said",
    traits: { softness: 2, cinematic: 2, focus: 1 },
    feedback: "+ Classical quiet",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #f1f5f9, #e2e8f0)",
    whyText: "88 keys and all the feelings that need no explanation.",
    boostGenres: ["classical", "jazz", "instrumental"],
  },
  {
    id: "lo-fi-beats",
    emoji: "📻",
    title: "Lo-fi beats",
    subtitle: "Vinyl crackle and homework mode",
    traits: { softness: 2, focus: 2, warmth: 1 },
    feedback: "+ Lo-fi glow",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #fef3c7, #fed7aa)",
    whyText: "The crackling is part of the sound. Imperfect is the point.",
    boostGenres: ["lo-fi", "instrumental"],
  },
  {
    id: "big-drops",
    emoji: "💥",
    title: "Big drops",
    subtitle: "Built for the moment everything hits",
    traits: { energy: 3, tempo: 2, chaos: 2 },
    feedback: "+ Drop incoming",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #fce7f3, #a855f7)",
    whyText: "The buildup is permission. The drop is the point.",
    boostGenres: ["edm"],
  },
  {
    id: "acoustic-morning",
    emoji: "🎸",
    title: "Acoustic morning",
    subtitle: "Before the world starts",
    traits: { softness: 3, warmth: 2, romance: 1 },
    feedback: "+ Acoustic soft",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #fef9c3, #fef3c7)",
    whyText: "Strings and silence. The hour before everyone else wakes up.",
    boostGenres: ["folk", "indie", "acoustic", "country"],
  },
  {
    id: "no-lyrics",
    emoji: "🎼",
    title: "No lyrics, please",
    subtitle: "Words get in the way",
    traits: { focus: 3, softness: 1 },
    feedback: "+ Pure sound",
    cardType: "sound",
    gradient: "linear-gradient(135deg, #ecfdf5, #d1fae5)",
    whyText: "Your thoughts are the lyrics. The music is just the beat.",
    boostGenres: ["instrumental", "lo-fi", "classical", "electronic", "jazz"],
    boostLanguages: ["instrumental"],
  },

  /* ── Genre ── */
  {
    id: "kpop-energy",
    emoji: "✨",
    title: "K-pop energy",
    subtitle: "Produced within an inch of perfection",
    traits: { tempo: 2, confidence: 2, energy: 1 },
    feedback: "+ K-pop",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #fce7f3, #f9a8d4)",
    whyText: "Every frame choreographed. Every beat engineered to stick.",
    boostGenres: ["k-pop"],
    boostLanguages: ["korean"],
  },
  {
    id: "afrobeats-sunshine",
    emoji: "🌍",
    title: "Afrobeats sunshine",
    subtitle: "Lagos heat, global wave",
    traits: { warmth: 2, tempo: 2, energy: 1 },
    feedback: "+ Afrobeats",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #fef9c3, #fbbf24)",
    whyText: "Rhythm before everything. The groove finds you, not the other way.",
    boostGenres: ["afrobeats", "amapiano"],
    boostRegions: ["nigeria", "south-africa", "ghana"],
  },
  {
    id: "latin-party",
    emoji: "🪇",
    title: "Latin party",
    subtitle: "Hips don't lie, neither does the bassline",
    traits: { energy: 2, tempo: 3, confidence: 1 },
    feedback: "+ Latin heat",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #fef08a, #fb923c)",
    whyText: "The tempo is medicine. The perreo is non-optional.",
    boostGenres: ["reggaeton", "latin-pop"],
    boostLanguages: ["spanish"],
    boostRegions: ["latin-america"],
  },
  {
    id: "bollywood-drama",
    emoji: "🎬",
    title: "Bollywood drama",
    subtitle: "Big feelings, bigger production",
    traits: { cinematic: 3, romance: 2, energy: 1 },
    feedback: "+ Bollywood",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #fce7f3, #f9a8d4)",
    whyText: "Every scene is a music video. You deserve that soundtrack too.",
    boostGenres: ["bollywood"],
    boostLanguages: ["hindi"],
    boostRegions: ["south-asia"],
  },
  {
    id: "hip-hop-bars",
    emoji: "🎤",
    title: "Hip-hop bars",
    subtitle: "Words that land like punches",
    traits: { confidence: 2, aggression: 1, tempo: 1 },
    feedback: "+ Hip-hop",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #1e1b4b, #3730a3)",
    whyText: "Lyrics aren't decoration. They're the whole point.",
    boostGenres: ["hip-hop"],
  },
  {
    id: "jazz-mood",
    emoji: "🎷",
    title: "Jazz mood",
    subtitle: "Improvised and irreplaceable",
    traits: { focus: 2, softness: 1, warmth: 1 },
    feedback: "+ Jazz",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #fef9c3, #fde68a)",
    whyText: "The notes between the notes. Time is a suggestion.",
    boostGenres: ["jazz"],
  },
  {
    id: "metal-riffs",
    emoji: "🤘",
    title: "Metal riffs",
    subtitle: "Controlled fury",
    traits: { aggression: 3, energy: 2, darkness: 1 },
    feedback: "+ Metal",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #1c1917, #292524)",
    whyText: "The distortion is the emotion. Nothing soft needed here.",
    boostGenres: ["metal", "rock"],
  },
  {
    id: "indie-folk",
    emoji: "🌿",
    title: "Indie folk",
    subtitle: "Earned sadness, earned beauty",
    traits: { softness: 2, romance: 1, warmth: 1 },
    feedback: "+ Indie",
    cardType: "genre",
    gradient: "linear-gradient(135deg, #ecfdf5, #d1fae5)",
    whyText: "Imperfect voices telling perfect truths.",
    boostGenres: ["indie", "folk"],
  },

  /* ── Anti-genre ── */
  {
    id: "no-country",
    emoji: "🚫",
    title: "No country, please",
    subtitle: "Skip the cowboy sadness",
    traits: {},
    feedback: "No cowboy sadness. Got it.",
    cardType: "antiGenre",
    gradient: "linear-gradient(135deg, #fee2e2, #fca5a5)",
    whyText: "You've got your own sadness. You don't need a barn metaphor.",
    blockGenres: ["country"],
  },
  {
    id: "no-sad-songs",
    emoji: "🚫",
    title: "No sad songs",
    subtitle: "Good vibes only, enforced",
    traits: { energy: 1, warmth: 1 },
    feedback: "Sadness: filtered out.",
    cardType: "antiGenre",
    gradient: "linear-gradient(135deg, #fef3c7, #fde68a)",
    whyText: "Today is not a crying-in-the-car day. Today is a volume-up day.",
    blockGenres: ["lo-fi"],
  },
  {
    id: "no-heavy-metal",
    emoji: "🚫",
    title: "No screaming guitars",
    subtitle: "The riff is too much today",
    traits: { softness: 1 },
    feedback: "Keeping it gentle.",
    cardType: "antiGenre",
    gradient: "linear-gradient(135deg, #ecfdf5, #bbf7d0)",
    whyText: "Sometimes the distortion pedal needs a day off.",
    blockGenres: ["metal"],
  },
  {
    id: "no-edm",
    emoji: "🚫",
    title: "No DJ drops",
    subtitle: "Too many festival memories",
    traits: { softness: 1, focus: 1 },
    feedback: "Drop-free zone activated.",
    cardType: "antiGenre",
    gradient: "linear-gradient(135deg, #ede9fe, #ddd6fe)",
    whyText: "You're not in a field at 2am. You're in your kitchen. Different rules.",
    blockGenres: ["edm"],
  },

  /* ── Mood ── */
  {
    id: "gym-villain",
    emoji: "😈",
    title: "Gym villain mode",
    subtitle: "The final rep is personal",
    traits: { aggression: 2, confidence: 2, energy: 2 },
    feedback: "+ Villain arc",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #450a0a, #dc2626)",
    whyText: "You're not working out. You're performing a threat display.",
  },
  {
    id: "victory-lap",
    emoji: "🏆",
    title: "Victory lap",
    subtitle: "You won. The playlist should know.",
    traits: { confidence: 3, energy: 2, warmth: 1 },
    feedback: "+ Victory",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fef9c3, #fbbf24)",
    whyText: "This song plays when you remember you already did the hard thing.",
  },
  {
    id: "midnight-overthinking",
    emoji: "🌑",
    title: "Midnight overthinking",
    subtitle: "3am and it's getting specific",
    traits: { darkness: 2, cinematic: 1, romance: 1 },
    feedback: "+ Overthought",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #0f0f23, #1e1b4b)",
    whyText: "Your brain is writing a screenplay at 3am. Cast it properly.",
  },
  {
    id: "sunday-morning",
    emoji: "☀️",
    title: "Sunday morning",
    subtitle: "No plans, no rush, no problem",
    traits: { warmth: 3, softness: 2 },
    feedback: "+ Sunday glow",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fef9c3, #fef3c7)",
    whyText: "Time moves differently on Sundays. The music should too.",
  },
  {
    id: "pregame-hype",
    emoji: "🎯",
    title: "Pre-game hype",
    subtitle: "Getting in the zone before the moment",
    traits: { energy: 3, confidence: 2, tempo: 1 },
    feedback: "+ Locked in",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #dcfce7, #4ade80)",
    whyText: "The game hasn't started. The preparation soundtrack has.",
  },
  {
    id: "window-seat",
    emoji: "🚂",
    title: "Window seat feelings",
    subtitle: "Watching the world go by at speed",
    traits: { cinematic: 2, softness: 1, romance: 1 },
    feedback: "+ Cinematic gaze",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #e0e7ff, #c7d2fe)",
    whyText: "The best place to process everything is going 80mph past things you'll never see again.",
  },
  {
    id: "soft-chaos",
    emoji: "🌸",
    title: "Soft chaos",
    subtitle: "Gentle on the outside, spiraling inside",
    traits: { chaos: 2, softness: 1, romance: 1 },
    feedback: "+ Soft spiral",
    cardType: "mood",
    gradient: "linear-gradient(135deg, #fce7f3, #fbcfe8)",
    whyText: "Everything's fine. Everything's also falling apart. Somehow both.",
  },
  {
    id: "dark-club",
    emoji: "🌐",
    title: "Dark club",
    subtitle: "Smoke machine, no eye contact, perfect",
    traits: { darkness: 2, tempo: 2, confidence: 1 },
    feedback: "+ Underground",
    cardType: "lifestyle",
    gradient: "linear-gradient(135deg, #09090b, #18181b)",
    whyText: "The best clubs don't have signs. Neither do the playlists.",
    boostGenres: ["techno", "edm"],
  },

  /* ── Language / Region ── */
  {
    id: "korean-night-drive",
    emoji: "🇰🇷",
    title: "Korean night drive",
    subtitle: "Seoul at 2am hits different",
    traits: { cinematic: 2, darkness: 1, tempo: 1 },
    feedback: "+ Korean",
    cardType: "region",
    gradient: "linear-gradient(135deg, #fce7f3, #f9a8d4)",
    whyText: "Neon-lit highways and K-pop production values. Natural combination.",
    boostGenres: ["k-pop"],
    boostLanguages: ["korean"],
    boostRegions: ["south-korea"],
  },
  {
    id: "thai-pop-glow",
    emoji: "🇹🇭",
    title: "Thai pop glow",
    subtitle: "Bangkok vibes, global feeling",
    traits: { warmth: 2, energy: 1, tempo: 1 },
    feedback: "+ Thai",
    cardType: "language",
    gradient: "linear-gradient(135deg, #dcfce7, #86efac)",
    whyText: "T-Pop has its own wavelength. Once you're on it, you stay.",
    boostGenres: ["thai-pop"],
    boostLanguages: ["thai"],
    boostRegions: ["thailand"],
  },
  {
    id: "tokyo-neon-walk",
    emoji: "🗼",
    title: "Tokyo neon walk",
    subtitle: "City energy, island aesthetics",
    traits: { cinematic: 2, energy: 1, chaos: 1 },
    feedback: "+ Japanese",
    cardType: "region",
    gradient: "linear-gradient(135deg, #ede9fe, #ddd6fe)",
    whyText: "J-pop has always understood that cities are characters, not backgrounds.",
    boostGenres: ["j-pop"],
    boostLanguages: ["japanese"],
    boostRegions: ["japan"],
  },
  {
    id: "french-cafe",
    emoji: "🥐",
    title: "French café",
    subtitle: "Existential and stylish",
    traits: { softness: 2, romance: 2, confidence: 1 },
    feedback: "+ French",
    cardType: "region",
    gradient: "linear-gradient(135deg, #fef9c3, #fef3c7)",
    whyText: "Being melancholic and well-dressed at the same time. A skill.",
    boostLanguages: ["french"],
    boostRegions: ["europe"],
  },
  {
    id: "lagos-everywhere",
    emoji: "🌍",
    title: "Lagos everywhere",
    subtitle: "Afrobeats crossed every border already",
    traits: { warmth: 2, tempo: 2, energy: 1 },
    feedback: "+ Afrobeats",
    cardType: "region",
    gradient: "linear-gradient(135deg, #fef9c3, #fbbf24)",
    whyText: "Lagos exported the groove. The rest of the world kept it.",
    boostGenres: ["afrobeats", "amapiano"],
    boostRegions: ["nigeria", "ghana", "south-africa"],
  },
  {
    id: "punjabi-heat",
    emoji: "🔥",
    title: "Punjabi heat",
    subtitle: "Diaspora energy, global reach",
    traits: { confidence: 2, energy: 2, warmth: 1 },
    feedback: "+ Punjabi",
    cardType: "language",
    gradient: "linear-gradient(135deg, #fef3c7, #fb923c)",
    whyText: "The dhol beat finds you wherever you are. You just have to accept it.",
    boostGenres: ["punjabi"],
    boostLanguages: ["punjabi"],
    boostRegions: ["south-asia"],
  },
  {
    id: "hindi-cinema",
    emoji: "🎞️",
    title: "Hindi cinema",
    subtitle: "Romance at feature-film scale",
    traits: { cinematic: 2, romance: 2, warmth: 1 },
    feedback: "+ Bollywood",
    cardType: "language",
    gradient: "linear-gradient(135deg, #fce7f3, #f9a8d4)",
    whyText: "Bollywood doesn't do small feelings. Neither do you.",
    boostGenres: ["bollywood"],
    boostLanguages: ["hindi"],
  },
  {
    id: "spanish-sun",
    emoji: "🌞",
    title: "Spanish sun",
    subtitle: "Latin heat, zero explanations needed",
    traits: { warmth: 2, energy: 2, confidence: 1 },
    feedback: "+ Latin",
    cardType: "region",
    gradient: "linear-gradient(135deg, #fef9c3, #fb923c)",
    whyText: "The rhythm is the language. You don't need to understand the words.",
    boostLanguages: ["spanish"],
    boostRegions: ["latin-america", "europe"],
  },
];

/* ================================================================== */
/* SCENARIOS                                                           */
/* ================================================================== */

export const FALLBACK_SCENARIOS: Scenario[] = [
  {
    id: "drive",
    emoji: "🚗",
    label: "Drive",
    tagline: "Windows down or midnight run",
    baseTraits: { cinematic: 2, tempo: 1, energy: 1 },
    deck: [
      "late-night-highway",
      "road-trip",
      "dark-rooms",
      "main-character",
      "beach-sunset",
      "rainy-days",
      "restless-energy",
      "window-seat",
    ],
  },
  {
    id: "gym",
    emoji: "🏋️",
    label: "Gym",
    tagline: "Lift heavy, feel unstoppable",
    baseTraits: { energy: 2, aggression: 2, tempo: 1 },
    deck: [
      "boxing",
      "gym-villain",
      "restless-energy",
      "main-character",
      "feeling-expensive",
      "spicy-food",
      "fast-drums",
      "pregame-hype",
    ],
  },
  {
    id: "focus",
    emoji: "💻",
    label: "Focus",
    tagline: "Lock in, tune out",
    baseTraits: { focus: 2, softness: 1 },
    deck: [
      "deep-work",
      "coffee-shop",
      "rainy-days",
      "no-lyrics",
      "lo-fi-beats",
      "walking-fast",
      "piano-only",
      "sunday-morning",
    ],
  },
  {
    id: "party",
    emoji: "🎉",
    label: "Party",
    tagline: "Tonight has potential",
    baseTraits: { energy: 2, tempo: 2, chaos: 1 },
    deck: [
      "dance-floor",
      "latin-party",
      "afrobeats-sunshine",
      "dark-club",
      "big-drops",
      "feeling-expensive",
      "restless-energy",
      "pregame-hype",
    ],
  },
  {
    id: "sad",
    emoji: "😔",
    label: "Sad",
    tagline: "Feel it all the way through",
    baseTraits: { darkness: 1, softness: 1, romance: 1 },
    deck: [
      "heartbreak-montage",
      "rainy-days",
      "midnight-overthinking",
      "window-seat",
      "coffee-shop",
      "acoustic-morning",
      "soft-chaos",
      "beach-sunset",
    ],
  },
  {
    id: "chill",
    emoji: "😌",
    label: "Chill",
    tagline: "Low stakes, high vibes",
    baseTraits: { softness: 2, warmth: 2 },
    deck: [
      "beach-sunset",
      "sunday-morning",
      "coffee-shop",
      "lo-fi-beats",
      "road-trip",
      "indie-folk",
      "jazz-mood",
      "acoustic-morning",
    ],
  },
  {
    id: "random",
    emoji: "🎲",
    label: "Random Me",
    tagline: "Surprise me, I contain multitudes",
    baseTraits: {},
    deck: [],
  },
];

/* ================================================================== */
/* SONGS (150+)                                                        */
/* ================================================================== */

export const FALLBACK_SONGS: Song[] = [
  /* ─────────── English – R&B / Pop ─────────── */
  {
    id: "after-hours-the-weeknd",
    title: "After Hours",
    artist: "The Weeknd",
    language: "english",
    region: "north-america",
    genres: ["r&b", "pop"],
    era: "2020s",
    platforms: {},
    traits: { darkness: 3, cinematic: 2, energy: 2, tempo: 1 },
    scenarios: ["drive", "sad"],
    chips: [{ emoji: "🌙", label: "Night drive" }, { emoji: "🖤", label: "Dark" }],
    popularity: 90,
  },
  {
    id: "blinding-lights-the-weeknd",
    title: "Blinding Lights",
    artist: "The Weeknd",
    language: "english",
    region: "north-america",
    genres: ["pop", "synth-pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 3, tempo: 3, cinematic: 2, romance: 1 },
    scenarios: ["drive", "party", "gym"],
    chips: [{ emoji: "🌃", label: "City night" }, { emoji: "⚡", label: "Synth rush" }],
    popularity: 96,
  },
  {
    id: "good-days-sza",
    title: "Good Days",
    artist: "SZA",
    language: "english",
    region: "north-america",
    genres: ["r&b"],
    era: "2020s",
    platforms: {},
    traits: { softness: 3, warmth: 2, romance: 2 },
    scenarios: ["chill", "sad", "focus"],
    chips: [{ emoji: "🪶", label: "Soft" }, { emoji: "🌅", label: "Warm glow" }],
    popularity: 87,
  },
  {
    id: "nights-frank-ocean",
    title: "Nights",
    artist: "Frank Ocean",
    language: "english",
    region: "north-america",
    genres: ["r&b"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, romance: 2, cinematic: 2, darkness: 1 },
    scenarios: ["sad", "chill", "drive"],
    chips: [{ emoji: "💔", label: "Two moods" }, { emoji: "🌙", label: "Late night" }],
    popularity: 91,
  },
  {
    id: "adorn-miguel",
    title: "Adorn",
    artist: "Miguel",
    language: "english",
    region: "north-america",
    genres: ["r&b"],
    era: "2010s",
    platforms: {},
    traits: { romance: 3, warmth: 2, softness: 2 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "💘", label: "Slow burn" }, { emoji: "🌅", label: "Soul" }],
    popularity: 80,
  },
  {
    id: "see-you-again-tyler-the-creator",
    title: "See You Again",
    artist: "Tyler, The Creator",
    language: "english",
    region: "north-america",
    genres: ["r&b", "hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 3, softness: 2, warmth: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [{ emoji: "💘", label: "Dreamy" }, { emoji: "🪶", label: "Soft" }],
    popularity: 88,
  },
  {
    id: "redbone-childish-gambino",
    title: "Redbone",
    artist: "Childish Gambino",
    language: "english",
    region: "north-america",
    genres: ["r&b", "funk"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 2, romance: 2, softness: 2, darkness: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "🌅", label: "Groove" }, { emoji: "💘", label: "Smooth" }],
    popularity: 88,
  },
  {
    id: "passionfruit-drake",
    title: "Passionfruit",
    artist: "Drake",
    language: "english",
    region: "north-america",
    genres: ["pop", "r&b"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, warmth: 2, romance: 2, tempo: 1 },
    scenarios: ["chill", "party", "sad"],
    chips: [{ emoji: "🏝️", label: "Tropical" }, { emoji: "🪶", label: "Smooth" }],
    popularity: 86,
  },
  {
    id: "anti-hero-taylor-swift",
    title: "Anti-Hero",
    artist: "Taylor Swift",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2020s",
    platforms: {},
    traits: { chaos: 2, softness: 1, romance: 1, confidence: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "🌪️", label: "Self-aware mess" }, { emoji: "🪶", label: "Confessional" }],
    popularity: 94,
  },
  {
    id: "espresso-sabrina-carpenter",
    title: "Espresso",
    artist: "Sabrina Carpenter",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 3, warmth: 2, tempo: 2 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "☕", label: "Confident" }, { emoji: "👑", label: "Effortless" }],
    popularity: 91,
  },
  {
    id: "as-it-was-harry-styles",
    title: "As It Was",
    artist: "Harry Styles",
    language: "english",
    region: "europe",
    genres: ["pop", "indie"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 1, tempo: 2, cinematic: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [{ emoji: "🌅", label: "Bittersweet" }, { emoji: "🥁", label: "Driving beat" }],
    popularity: 90,
  },
  {
    id: "flowers-miley-cyrus",
    title: "Flowers",
    artist: "Miley Cyrus",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 3, warmth: 1, tempo: 2 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "👑", label: "Self-love" }, { emoji: "🌸", label: "Glow-up" }],
    popularity: 93,
  },

  /* ─────────── English – Hip-hop ─────────── */
  {
    id: "humble-kendrick-lamar",
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, aggression: 2, energy: 2 },
    scenarios: ["gym", "party", "drive"],
    chips: [{ emoji: "👑", label: "Confidence" }, { emoji: "🥊", label: "Hard-hitting" }],
    popularity: 92,
  },
  {
    id: "god-plan-drake",
    title: "God's Plan",
    artist: "Drake",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 2, warmth: 2, tempo: 1 },
    scenarios: ["party", "drive", "chill"],
    chips: [{ emoji: "👑", label: "Golden" }, { emoji: "🌅", label: "Triumphant" }],
    popularity: 90,
  },
  {
    id: "all-falls-down-kanye",
    title: "All Falls Down",
    artist: "Kanye West",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2000s",
    platforms: {},
    traits: { cinematic: 2, romance: 1, softness: 1, focus: 1 },
    scenarios: ["sad", "chill", "drive"],
    chips: [{ emoji: "🎬", label: "Introspective" }, { emoji: "💔", label: "Honest" }],
    popularity: 82,
  },
  {
    id: "power-kanye-west",
    title: "POWER",
    artist: "Kanye West",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, energy: 3, aggression: 1 },
    scenarios: ["gym", "party"],
    chips: [{ emoji: "👑", label: "Main character" }, { emoji: "⚡", label: "Energy" }],
    popularity: 90,
  },
  {
    id: "alright-kendrick",
    title: "Alright",
    artist: "Kendrick Lamar",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 2, energy: 2, warmth: 1 },
    scenarios: ["drive", "gym", "party"],
    chips: [{ emoji: "✊", label: "Triumphant" }, { emoji: "🌅", label: "Resilient" }],
    popularity: 84,
  },
  {
    id: "no-role-modelz-j-cole",
    title: "No Role Modelz",
    artist: "J. Cole",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 2, warmth: 1, focus: 1, tempo: 1 },
    scenarios: ["chill", "drive", "party"],
    chips: [{ emoji: "👑", label: "Self-made" }, { emoji: "🌅", label: "Laid-back" }],
    popularity: 88,
  },
  {
    id: "goosebumps-travis-scott",
    title: "goosebumps",
    artist: "Travis Scott",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 2, energy: 2, chaos: 1, tempo: 1 },
    scenarios: ["party", "drive", "gym"],
    chips: [{ emoji: "🌙", label: "Late night" }, { emoji: "🌪️", label: "Hypnotic" }],
    popularity: 89,
  },
  {
    id: "the-search-nf",
    title: "The Search",
    artist: "NF",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2010s",
    platforms: {},
    traits: { aggression: 2, darkness: 2, energy: 2, focus: 1 },
    scenarios: ["gym", "drive"],
    chips: [{ emoji: "🥊", label: "Aggression" }, { emoji: "🧠", label: "Introspective" }],
    popularity: 74,
  },
  {
    id: "superhero-metro-boomin",
    title: "Superhero (Heroes & Villains)",
    artist: "Metro Boomin",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { darkness: 2, confidence: 2, cinematic: 2 },
    scenarios: ["gym", "drive", "party"],
    chips: [{ emoji: "🎬", label: "Villain arc" }, { emoji: "🖤", label: "Dark" }],
    popularity: 85,
  },
  {
    id: "till-i-collapse-eminem",
    title: "Till I Collapse",
    artist: "Eminem",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2000s",
    platforms: {},
    traits: { aggression: 3, energy: 3, confidence: 2 },
    scenarios: ["gym"],
    chips: [{ emoji: "🥊", label: "Last rep" }, { emoji: "⚡", label: "Relentless" }],
    popularity: 90,
  },
  {
    id: "needed-me-rihanna",
    title: "Needed Me",
    artist: "Rihanna",
    language: "english",
    region: "caribbean",
    genres: ["r&b", "pop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, darkness: 2, softness: 1 },
    scenarios: ["party", "drive", "gym"],
    chips: [{ emoji: "👑", label: "Savage" }, { emoji: "🖤", label: "Cold" }],
    popularity: 85,
  },

  /* ─────────── English – Pop / Indie / Rock ─────────── */
  {
    id: "bury-a-friend-billie-eilish",
    title: "bury a friend",
    artist: "Billie Eilish",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 3, chaos: 2, cinematic: 1 },
    scenarios: ["sad", "drive", "gym"],
    chips: [{ emoji: "🖤", label: "Eerie" }, { emoji: "🌪️", label: "Unhinged" }],
    popularity: 84,
  },
  {
    id: "physical-dua-lipa",
    title: "Physical",
    artist: "Dua Lipa",
    language: "english",
    region: "europe",
    genres: ["pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 3, tempo: 3, confidence: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "⚡", label: "Cardio" }, { emoji: "🕺", label: "Movement" }],
    popularity: 82,
  },
  {
    id: "do-i-wanna-know-arctic-monkeys",
    title: "Do I Wanna Know?",
    artist: "Arctic Monkeys",
    language: "english",
    region: "europe",
    genres: ["rock", "indie"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 2, romance: 2, confidence: 1, cinematic: 1 },
    scenarios: ["drive", "sad", "gym"],
    chips: [{ emoji: "🖤", label: "Brooding" }, { emoji: "💘", label: "Tension" }],
    popularity: 90,
  },
  {
    id: "mr-brightside-killers",
    title: "Mr. Brightside",
    artist: "The Killers",
    language: "english",
    region: "north-america",
    genres: ["rock", "indie"],
    era: "2000s",
    platforms: {},
    traits: { energy: 3, chaos: 2, romance: 2, tempo: 2 },
    scenarios: ["party", "sad", "drive"],
    chips: [{ emoji: "🌪️", label: "Spiral" }, { emoji: "⚡", label: "Unstoppable" }],
    popularity: 91,
  },
  {
    id: "take-me-to-church-hozier",
    title: "Take Me to Church",
    artist: "Hozier",
    language: "english",
    region: "europe",
    genres: ["rock", "indie"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 2, romance: 3, cinematic: 2 },
    scenarios: ["sad", "drive"],
    chips: [{ emoji: "🕯️", label: "Sacred" }, { emoji: "💔", label: "Devotion" }],
    popularity: 88,
  },
  {
    id: "let-it-happen-tame-impala",
    title: "Let It Happen",
    artist: "Tame Impala",
    language: "english",
    region: "oceania",
    genres: ["indie", "rock"],
    era: "2010s",
    platforms: {},
    traits: { chaos: 2, cinematic: 2, energy: 2, tempo: 2, focus: 1 },
    scenarios: ["drive", "focus", "party"],
    chips: [{ emoji: "🌪️", label: "Spiraling" }, { emoji: "🎬", label: "Epic build" }],
    popularity: 85,
  },
  {
    id: "glimpse-of-us-joji",
    title: "Glimpse of Us",
    artist: "Joji",
    language: "english",
    region: "north-america",
    genres: ["pop", "lo-fi"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, softness: 3, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "💔", label: "Heartbreak" }, { emoji: "🪶", label: "Fragile" }],
    popularity: 85,
  },
  {
    id: "circles-post-malone",
    title: "Circles",
    artist: "Post Malone",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, warmth: 1, romance: 1, darkness: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [{ emoji: "🪶", label: "Easy" }, { emoji: "💔", label: "Bittersweet" }],
    popularity: 84,
  },
  {
    id: "motion-sickness-phoebe-bridgers",
    title: "Motion Sickness",
    artist: "Phoebe Bridgers",
    language: "english",
    region: "north-america",
    genres: ["indie"],
    era: "2010s",
    platforms: {},
    traits: { romance: 2, softness: 2, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "💔", label: "Bittersweet" }, { emoji: "🌧️", label: "Indie ache" }],
    popularity: 75,
  },
  {
    id: "holocene-bon-iver",
    title: "Holocene",
    artist: "Bon Iver",
    language: "english",
    region: "north-america",
    genres: ["indie", "folk"],
    era: "2010s",
    platforms: {},
    traits: { softness: 3, cinematic: 2, warmth: 1, romance: 1 },
    scenarios: ["sad", "chill", "focus"],
    chips: [{ emoji: "🌧️", label: "Quiet awe" }, { emoji: "🎬", label: "Wide open" }],
    popularity: 80,
  },
  {
    id: "summertime-sadness-lana-del-rey",
    title: "Summertime Sadness",
    artist: "Lana Del Rey",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 2, romance: 2, darkness: 2, warmth: 1 },
    scenarios: ["sad", "drive", "chill"],
    chips: [{ emoji: "🎬", label: "Tragic glam" }, { emoji: "💔", label: "Summer ache" }],
    popularity: 86,
  },
  {
    id: "someone-like-you-adele",
    title: "Someone Like You",
    artist: "Adele",
    language: "english",
    region: "europe",
    genres: ["pop", "soul"],
    era: "2010s",
    platforms: {},
    traits: { romance: 3, softness: 3, cinematic: 1 },
    scenarios: ["sad"],
    chips: [{ emoji: "💔", label: "Devastating" }, { emoji: "🎹", label: "Pure" }],
    popularity: 92,
  },

  /* ─────────── English – EDM / Electronic ─────────── */
  {
    id: "levels-avicii",
    title: "Levels",
    artist: "Avicii",
    language: "english",
    region: "europe",
    genres: ["edm"],
    era: "2010s",
    platforms: {},
    traits: { energy: 3, tempo: 3, warmth: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "⚡", label: "Festival" }, { emoji: "🌅", label: "Euphoric" }],
    popularity: 88,
  },
  {
    id: "pursuit-gesaffelstein",
    title: "Pursuit",
    artist: "Gesaffelstein",
    language: "instrumental",
    region: "europe",
    genres: ["edm", "techno"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 3, aggression: 2, cinematic: 2, tempo: 2 },
    scenarios: ["gym", "drive", "party"],
    chips: [{ emoji: "🖤", label: "Dark techno" }, { emoji: "🎬", label: "Cinematic" }],
    popularity: 70,
  },
  {
    id: "a-moment-apart-odesza",
    title: "A Moment Apart",
    artist: "ODESZA",
    language: "instrumental",
    region: "north-america",
    genres: ["edm"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 3, warmth: 2, energy: 1, focus: 1 },
    scenarios: ["focus", "chill", "drive"],
    chips: [{ emoji: "🎬", label: "Cinematic" }, { emoji: "🌅", label: "Euphoric" }],
    popularity: 72,
  },
  {
    id: "midnight-city-m83",
    title: "Midnight City",
    artist: "M83",
    language: "english",
    region: "europe",
    genres: ["edm", "indie"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 3, energy: 2, tempo: 2, warmth: 1 },
    scenarios: ["drive", "party", "focus"],
    chips: [{ emoji: "🌃", label: "City lights" }, { emoji: "🎬", label: "Movie ending" }],
    popularity: 86,
  },
  {
    id: "delilah-fred-again",
    title: "Delilah (pull me out of this)",
    artist: "Fred again..",
    language: "english",
    region: "europe",
    genres: ["edm"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, romance: 1, chaos: 1, focus: 1 },
    scenarios: ["party", "focus", "drive"],
    chips: [{ emoji: "🕺", label: "Late-night dance" }, { emoji: "💘", label: "Emotional" }],
    popularity: 83,
  },
  {
    id: "latch-disclosure",
    title: "Latch",
    artist: "Disclosure",
    language: "english",
    region: "europe",
    genres: ["edm"],
    era: "2010s",
    platforms: {},
    traits: { energy: 2, romance: 2, tempo: 2, warmth: 1 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "🕺", label: "Dance" }, { emoji: "💘", label: "Euphoric" }],
    popularity: 81,
  },
  {
    id: "feel-so-close-calvin-harris",
    title: "Feel So Close",
    artist: "Calvin Harris",
    language: "english",
    region: "europe",
    genres: ["edm"],
    era: "2010s",
    platforms: {},
    traits: { energy: 2, warmth: 2, tempo: 2, romance: 1 },
    scenarios: ["party", "gym", "drive"],
    chips: [{ emoji: "⚡", label: "Festival" }, { emoji: "🌅", label: "Feel-good" }],
    popularity: 80,
  },
  {
    id: "instant-crush-daft-punk",
    title: "Instant Crush",
    artist: "Daft Punk",
    language: "english",
    region: "europe",
    genres: ["edm", "pop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 2, cinematic: 1, softness: 1, tempo: 1, warmth: 1 },
    scenarios: ["drive", "chill", "sad"],
    chips: [{ emoji: "💘", label: "Wistful" }, { emoji: "🌃", label: "Synth glow" }],
    popularity: 84,
  },
  {
    id: "uptown-funk-mark-ronson",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    language: "english",
    region: "north-america",
    genres: ["pop", "funk"],
    era: "2010s",
    platforms: {},
    traits: { energy: 3, tempo: 3, confidence: 2, warmth: 1 },
    scenarios: ["party"],
    chips: [{ emoji: "🕺", label: "Instant party" }, { emoji: "👑", label: "Swagger" }],
    popularity: 87,
  },

  /* ─────────── English – Instrumental / Focus ─────────── */
  {
    id: "awake-tycho",
    title: "Awake",
    artist: "Tycho",
    language: "instrumental",
    region: "north-america",
    genres: ["electronic", "lo-fi"],
    era: "2010s",
    platforms: {},
    traits: { focus: 3, warmth: 2, softness: 2 },
    scenarios: ["focus", "chill"],
    chips: [{ emoji: "🧠", label: "Instrumental" }, { emoji: "🌅", label: "Glow" }],
    popularity: 65,
  },
  {
    id: "kerala-bonobo",
    title: "Kerala",
    artist: "Bonobo",
    language: "instrumental",
    region: "europe",
    genres: ["electronic"],
    era: "2010s",
    platforms: {},
    traits: { focus: 3, tempo: 1, softness: 1, cinematic: 1 },
    scenarios: ["focus", "chill"],
    chips: [{ emoji: "🧠", label: "Flow state" }, { emoji: "🥁", label: "Pulse" }],
    popularity: 68,
  },
  {
    id: "death-bed-powfu",
    title: "death bed (coffee for your head)",
    artist: "Powfu",
    language: "english",
    region: "north-america",
    genres: ["lo-fi", "pop"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 1, darkness: 1, focus: 1 },
    scenarios: ["sad", "chill", "focus"],
    chips: [{ emoji: "🪶", label: "Bedroom lo-fi" }, { emoji: "💔", label: "Soft sad" }],
    popularity: 78,
  },
  {
    id: "day-n-nite-kid-cudi",
    title: "Day 'N' Nite",
    artist: "Kid Cudi",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2000s",
    platforms: {},
    traits: { darkness: 2, focus: 1, softness: 1, cinematic: 1 },
    scenarios: ["drive", "sad", "focus"],
    chips: [{ emoji: "🌙", label: "Night loner" }, { emoji: "🖤", label: "Moody" }],
    popularity: 82,
  },

  /* ─────────── English – Country / Jazz / Metal ─────────── */
  {
    id: "tennessee-whiskey-chris-stapleton",
    title: "Tennessee Whiskey",
    artist: "Chris Stapleton",
    language: "english",
    region: "north-america",
    genres: ["country", "soul"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 3, romance: 2, softness: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "🥃", label: "Slow burn" }, { emoji: "🌅", label: "Porch light" }],
    popularity: 84,
  },
  {
    id: "jolene-dolly-parton",
    title: "Jolene",
    artist: "Dolly Parton",
    language: "english",
    region: "north-america",
    genres: ["country"],
    era: "1970s",
    platforms: {},
    traits: { romance: 3, cinematic: 1, darkness: 1 },
    scenarios: ["sad", "drive"],
    chips: [{ emoji: "💔", label: "Please don't" }, { emoji: "🎸", label: "Classic" }],
    popularity: 86,
  },
  {
    id: "master-of-puppets-metallica",
    title: "Master of Puppets",
    artist: "Metallica",
    language: "english",
    region: "north-america",
    genres: ["metal"],
    era: "1980s",
    platforms: {},
    traits: { aggression: 3, energy: 3, darkness: 1, tempo: 1 },
    scenarios: ["gym"],
    chips: [{ emoji: "🥊", label: "Riff cardio" }, { emoji: "⚡", label: "Full throttle" }],
    popularity: 88,
  },
  {
    id: "smells-like-teen-spirit-nirvana",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    language: "english",
    region: "north-america",
    genres: ["rock"],
    era: "1990s",
    platforms: {},
    traits: { chaos: 3, aggression: 2, energy: 3 },
    scenarios: ["gym", "party"],
    chips: [{ emoji: "🌪️", label: "Generation-defining" }, { emoji: "🥊", label: "Raw" }],
    popularity: 91,
  },
  {
    id: "take-five-dave-brubeck",
    title: "Take Five",
    artist: "Dave Brubeck",
    language: "instrumental",
    region: "north-america",
    genres: ["jazz"],
    era: "1950s",
    platforms: {},
    traits: { focus: 3, softness: 1, cinematic: 1 },
    scenarios: ["focus", "chill"],
    chips: [{ emoji: "🧠", label: "5/4 flow" }, { emoji: "🎷", label: "Timeless" }],
    popularity: 80,
  },
  {
    id: "feeling-good-nina-simone",
    title: "Feeling Good",
    artist: "Nina Simone",
    language: "english",
    region: "north-america",
    genres: ["jazz", "soul"],
    era: "1960s",
    platforms: {},
    traits: { confidence: 3, warmth: 2, cinematic: 2 },
    scenarios: ["chill", "drive", "party"],
    chips: [{ emoji: "👑", label: "New dawn" }, { emoji: "🎷", label: "Soul" }],
    popularity: 84,
  },

  /* ─────────── Spanish / Latin ─────────── */
  {
    id: "titi-me-pregunto-bad-bunny",
    title: "Tití Me Preguntó",
    artist: "Bad Bunny",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, confidence: 2, chaos: 1 },
    scenarios: ["party", "gym", "drive"],
    chips: [{ emoji: "🔥", label: "Global heat" }, { emoji: "🕺", label: "Perreo" }],
    popularity: 92,
  },
  {
    id: "despecha-rosalia",
    title: "DESPECHÁ",
    artist: "ROSALÍA",
    language: "spanish",
    region: "europe",
    genres: ["pop", "reggaeton"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 2, warmth: 2, confidence: 1 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "☀️", label: "Summer strut" }, { emoji: "🕺", label: "Light feet" }],
    popularity: 84,
  },
  {
    id: "mi-gente-j-balvin",
    title: "Mi Gente",
    artist: "J Balvin & Willy William",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton", "edm"],
    era: "2010s",
    platforms: {},
    traits: { energy: 3, tempo: 2, chaos: 1 },
    scenarios: ["party"],
    chips: [{ emoji: "🎉", label: "Instant party" }, { emoji: "🌎", label: "Borderless" }],
    popularity: 85,
  },
  {
    id: "provenza-karol-g",
    title: "PROVENZA",
    artist: "KAROL G",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton", "pop"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, softness: 2, tempo: 1, romance: 1 },
    scenarios: ["chill", "party"],
    chips: [{ emoji: "🏝️", label: "Beach pace" }, { emoji: "🌅", label: "Easy glow" }],
    popularity: 86,
  },
  {
    id: "gasolina-daddy-yankee",
    title: "Gasolina",
    artist: "Daddy Yankee",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton"],
    era: "2000s",
    platforms: {},
    traits: { energy: 3, tempo: 3, confidence: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "🔥", label: "Reggaeton founding" }, { emoji: "🕺", label: "Non-stop" }],
    popularity: 88,
  },
  {
    id: "bzrp-shakira",
    title: "Shakira: BZRP Music Sessions #53",
    artist: "Bizarrap & Shakira",
    language: "spanish",
    region: "latin-america",
    genres: ["pop", "latin-pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 3, energy: 2, tempo: 2 },
    scenarios: ["party", "gym", "drive"],
    chips: [{ emoji: "👑", label: "Unbothered" }, { emoji: "🔥", label: "Viral" }],
    popularity: 93,
  },
  {
    id: "me-porto-bonito-bad-bunny",
    title: "Me Porto Bonito",
    artist: "Bad Bunny & Chencho Corleone",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, romance: 2, tempo: 2 },
    scenarios: ["chill", "party"],
    chips: [{ emoji: "🏝️", label: "Island summer" }, { emoji: "💘", label: "Smooth" }],
    popularity: 88,
  },
  {
    id: "hawai-maluma",
    title: "Hawái",
    artist: "Maluma",
    language: "spanish",
    region: "latin-america",
    genres: ["pop", "reggaeton"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, warmth: 2, tempo: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "🏝️", label: "Tropical" }, { emoji: "💔", label: "Island hurt" }],
    popularity: 86,
  },

  /* ─────────── Korean / K-pop ─────────── */
  {
    id: "super-shy-newjeans",
    title: "Super Shy",
    artist: "NewJeans",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 2, softness: 2, romance: 1, energy: 1 },
    scenarios: ["party", "chill", "focus"],
    chips: [{ emoji: "🫧", label: "Featherlight" }, { emoji: "🕺", label: "Skip-walk" }],
    popularity: 87,
  },
  {
    id: "ddu-du-ddu-du-blackpink",
    title: "DDU-DU DDU-DU",
    artist: "BLACKPINK",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, energy: 2, aggression: 1 },
    scenarios: ["gym", "party"],
    chips: [{ emoji: "👑", label: "Boss walk" }, { emoji: "🥊", label: "Swagger" }],
    popularity: 88,
  },
  {
    id: "supernova-aespa",
    title: "Supernova",
    artist: "aespa",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, chaos: 1, confidence: 1 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "⚡", label: "Hyper" }, { emoji: "🌪️", label: "Glitch-pop" }],
    popularity: 84,
  },
  {
    id: "spring-day-bts",
    title: "Spring Day",
    artist: "BTS",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, romance: 2, cinematic: 2, warmth: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "💔", label: "Missing someone" }, { emoji: "🎬", label: "Wide shot" }],
    popularity: 89,
  },
  {
    id: "ditto-newjeans",
    title: "Ditto",
    artist: "NewJeans",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 2, cinematic: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "📼", label: "Nostalgic" }, { emoji: "🪶", label: "Hazy" }],
    popularity: 86,
  },
  {
    id: "antifragile-le-sserafim",
    title: "ANTIFRAGILE",
    artist: "LE SSERAFIM",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 3, energy: 2, aggression: 1 },
    scenarios: ["gym", "party"],
    chips: [{ emoji: "💪", label: "Unbreakable" }, { emoji: "🔥", label: "Boss mode" }],
    popularity: 84,
  },
  {
    id: "celebrity-iu",
    title: "Celebrity",
    artist: "IU",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop", "pop"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, confidence: 2, softness: 1 },
    scenarios: ["chill", "party"],
    chips: [{ emoji: "⭐", label: "Sparkle" }, { emoji: "🌅", label: "Warm" }],
    popularity: 85,
  },
  {
    id: "love-dive-ive",
    title: "LOVE DIVE",
    artist: "IVE",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 2, romance: 2, tempo: 1 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "💘", label: "Dreamy flex" }, { emoji: "👑", label: "Self-assured" }],
    popularity: 83,
  },
  {
    id: "lalisa-lisa",
    title: "LALISA",
    artist: "LISA",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 3, energy: 2, tempo: 2 },
    scenarios: ["gym", "party"],
    chips: [{ emoji: "👑", label: "Solo era" }, { emoji: "🔥", label: "Flex" }],
    popularity: 87,
  },

  /* ─────────── Japanese / J-pop ─────────── */
  {
    id: "idol-yoasobi",
    title: "アイドル (Idol)",
    artist: "YOASOBI",
    language: "japanese",
    region: "japan",
    genres: ["j-pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, chaos: 2, cinematic: 1 },
    scenarios: ["party", "focus"],
    chips: [{ emoji: "⚡", label: "Hyper-pop rush" }, { emoji: "🎬", label: "Anime opening" }],
    popularity: 88,
  },
  {
    id: "shinunoga-e-wa-fujii-kaze",
    title: "Shinunoga E-Wa",
    artist: "Fujii Kaze",
    language: "japanese",
    region: "japan",
    genres: ["j-pop", "r&b"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, softness: 2, warmth: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "💘", label: "Devotion" }, { emoji: "🪶", label: "Smooth" }],
    popularity: 85,
  },
  {
    id: "kick-back-kenshi-yonezu",
    title: "KICK BACK",
    artist: "Kenshi Yonezu",
    language: "japanese",
    region: "japan",
    genres: ["j-pop", "rock"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, chaos: 2, aggression: 2 },
    scenarios: ["gym", "party"],
    chips: [{ emoji: "🌪️", label: "Unhinged" }, { emoji: "🥊", label: "Power-up" }],
    popularity: 84,
  },
  {
    id: "pretender-official-hige-dandism",
    title: "Pretender",
    artist: "Official HIGE DANdism",
    language: "japanese",
    region: "japan",
    genres: ["j-pop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 3, cinematic: 2, softness: 1 },
    scenarios: ["sad", "chill", "drive"],
    chips: [{ emoji: "💔", label: "Unrequited" }, { emoji: "🎬", label: "Sweeping" }],
    popularity: 85,
  },
  {
    id: "zenzenzense-radwimps",
    title: "前前前世 (Zenzenzense)",
    artist: "RADWIMPS",
    language: "japanese",
    region: "japan",
    genres: ["j-pop", "rock"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 3, energy: 2, romance: 2 },
    scenarios: ["drive", "party", "sad"],
    chips: [{ emoji: "🎬", label: "Anime film" }, { emoji: "🌪️", label: "Destined" }],
    popularity: 87,
  },

  /* ─────────── Hindi / Bollywood ─────────── */
  {
    id: "kesariya-arijit-singh",
    title: "Kesariya",
    artist: "Arijit Singh",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, warmth: 2, softness: 1, cinematic: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [{ emoji: "💘", label: "Golden romance" }, { emoji: "🎬", label: "Film moment" }],
    popularity: 90,
  },
  {
    id: "jhoome-jo-pathaan",
    title: "Jhoome Jo Pathaan",
    artist: "Arijit Singh & Vishal-Shekhhar",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, confidence: 1, cinematic: 1 },
    scenarios: ["party"],
    chips: [{ emoji: "🎉", label: "Blockbuster" }, { emoji: "🕺", label: "Full send" }],
    popularity: 82,
  },
  {
    id: "chaleya-arijit-singh",
    title: "Chaleya",
    artist: "Arijit Singh & Shilpa Rao",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, cinematic: 2, warmth: 1 },
    scenarios: ["sad", "chill", "drive"],
    chips: [{ emoji: "💘", label: "Longing" }, { emoji: "🎬", label: "Epic" }],
    popularity: 86,
  },
  {
    id: "tum-kya-mile",
    title: "Tum Kya Mile",
    artist: "Arijit Singh & Shreya Ghoshal",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, softness: 2, cinematic: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "💔", label: "Beautiful hurt" }, { emoji: "🌅", label: "Filmy" }],
    popularity: 84,
  },
  {
    id: "raataan-lambiyaan-jubin",
    title: "Raataan Lambiyan",
    artist: "Jubin Nautiyal & Asees Kaur",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, softness: 2, warmth: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "🌙", label: "Long nights" }, { emoji: "💘", label: "Tender" }],
    popularity: 82,
  },

  /* ─────────── Punjabi ─────────── */
  {
    id: "brown-munde-ap-dhillon",
    title: "Brown Munde",
    artist: "AP Dhillon",
    language: "punjabi",
    region: "south-asia",
    genres: ["punjabi", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 2, darkness: 1, energy: 1, cinematic: 1 },
    scenarios: ["gym", "drive"],
    chips: [{ emoji: "👑", label: "Quiet flex" }, { emoji: "🌙", label: "Late roll" }],
    popularity: 86,
  },
  {
    id: "295-sidhu-moose-wala",
    title: "295",
    artist: "Sidhu Moose Wala",
    language: "punjabi",
    region: "south-asia",
    genres: ["punjabi", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { darkness: 2, confidence: 2, cinematic: 1 },
    scenarios: ["drive", "gym"],
    chips: [{ emoji: "🖤", label: "Heavy legacy" }, { emoji: "👑", label: "Defiant" }],
    popularity: 87,
  },
  {
    id: "born-to-shine-diljit",
    title: "Born To Shine",
    artist: "Diljit Dosanjh",
    language: "punjabi",
    region: "south-asia",
    genres: ["punjabi", "pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 3, energy: 2, warmth: 1 },
    scenarios: ["party", "gym", "drive"],
    chips: [{ emoji: "🌟", label: "Diaspora pride" }, { emoji: "🔥", label: "Banger" }],
    popularity: 82,
  },

  /* ─────────── Afrobeats / Amapiano ─────────── */
  {
    id: "last-last-burna-boy",
    title: "Last Last",
    artist: "Burna Boy",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, romance: 1, darkness: 1, tempo: 1 },
    scenarios: ["chill", "sad", "party"],
    chips: [{ emoji: "💔", label: "Dancing through it" }, { emoji: "🌍", label: "Lagos everywhere" }],
    popularity: 88,
  },
  {
    id: "calm-down-rema",
    title: "Calm Down",
    artist: "Rema",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, romance: 2, tempo: 1 },
    scenarios: ["chill", "party"],
    chips: [{ emoji: "🌅", label: "Sweet talk" }, { emoji: "🕺", label: "Sway" }],
    popularity: 89,
  },
  {
    id: "essence-wizkid",
    title: "Essence",
    artist: "Wizkid ft. Tems",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 2, softness: 2, romance: 2 },
    scenarios: ["chill"],
    chips: [{ emoji: "🌅", label: "Honey-slow" }, { emoji: "💘", label: "Smooth" }],
    popularity: 88,
  },
  {
    id: "ye-burna-boy",
    title: "Ye",
    artist: "Burna Boy",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 2, warmth: 2, tempo: 1 },
    scenarios: ["chill", "party", "drive"],
    chips: [{ emoji: "🌍", label: "Afrofusion" }, { emoji: "☀️", label: "Lagos sun" }],
    popularity: 84,
  },
  {
    id: "love-nwantiti-ckay",
    title: "Love Nwantiti",
    artist: "CKay",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats", "pop"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, warmth: 2, tempo: 2 },
    scenarios: ["chill", "party"],
    chips: [{ emoji: "💘", label: "Viral" }, { emoji: "🌍", label: "Borderless" }],
    popularity: 90,
  },
  {
    id: "water-tyla",
    title: "Water",
    artist: "Tyla",
    language: "english",
    region: "south-africa",
    genres: ["amapiano", "pop"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 2, warmth: 2, romance: 1, confidence: 1 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "💧", label: "Amapiano bounce" }, { emoji: "🕺", label: "Hips first" }],
    popularity: 87,
  },
  {
    id: "mnike-tyler-icu",
    title: "Mnike",
    artist: "Tyler ICU & Tumelo.za",
    language: "zulu",
    region: "south-africa",
    genres: ["amapiano"],
    era: "2020s",
    platforms: {},
    traits: { tempo: 3, energy: 2, chaos: 1 },
    scenarios: ["party"],
    chips: [{ emoji: "🥁", label: "Log drum" }, { emoji: "🎉", label: "Ground-shake" }],
    popularity: 80,
  },
  {
    id: "ke-star-focalistic",
    title: "Ke Star",
    artist: "Focalistic & Davido",
    language: "english",
    region: "south-africa",
    genres: ["amapiano"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, warmth: 1 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "⭐", label: "Amapiano crossover" }, { emoji: "🌍", label: "Pan-African" }],
    popularity: 79,
  },

  /* ─────────── French ─────────── */
  {
    id: "alors-on-danse-stromae",
    title: "Alors on danse",
    artist: "Stromae",
    language: "french",
    region: "europe",
    genres: ["pop", "edm"],
    era: "2010s",
    platforms: {},
    traits: { tempo: 2, energy: 2, darkness: 1 },
    scenarios: ["party", "sad"],
    chips: [{ emoji: "🕺", label: "Dance anyway" }, { emoji: "🖤", label: "Bittersweet" }],
    popularity: 85,
  },
  {
    id: "djadja-aya-nakamura",
    title: "Djadja",
    artist: "Aya Nakamura",
    language: "french",
    region: "europe",
    genres: ["pop", "afrobeats"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 2, tempo: 2, warmth: 1 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "👑", label: "Unbothered" }, { emoji: "🕺", label: "Strut" }],
    popularity: 83,
  },
  {
    id: "derniere-danse-indila",
    title: "Dernière Danse",
    artist: "Indila",
    language: "french",
    region: "europe",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 2, romance: 2, darkness: 1, softness: 1 },
    scenarios: ["sad", "drive"],
    chips: [{ emoji: "🎬", label: "Rain-window opera" }, { emoji: "💔", label: "One last dance" }],
    popularity: 84,
  },
  {
    id: "papaoutai-stromae",
    title: "Papaoutai",
    artist: "Stromae",
    language: "french",
    region: "europe",
    genres: ["pop", "edm"],
    era: "2010s",
    platforms: {},
    traits: { cinematic: 2, darkness: 1, tempo: 1, romance: 1 },
    scenarios: ["sad", "drive"],
    chips: [{ emoji: "🎬", label: "Emotional" }, { emoji: "🖤", label: "Beautiful" }],
    popularity: 84,
  },
  {
    id: "la-vie-en-rose-edith-piaf",
    title: "La Vie en Rose",
    artist: "Édith Piaf",
    language: "french",
    region: "europe",
    genres: ["chanson", "pop"],
    era: "1940s",
    platforms: {},
    traits: { romance: 3, cinematic: 2, warmth: 2 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "🌹", label: "Timeless" }, { emoji: "💘", label: "Everything" }],
    popularity: 86,
  },

  /* ─────────── Arabic ─────────── */
  {
    id: "tamally-maak-amr-diab",
    title: "Tamally Maak",
    artist: "Amr Diab",
    language: "arabic",
    region: "middle-east",
    genres: ["arab-pop"],
    era: "2000s",
    platforms: {},
    traits: { romance: 3, warmth: 2, softness: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "💘", label: "Eternal" }, { emoji: "🌅", label: "Mediterranean" }],
    popularity: 85,
  },
  {
    id: "3-daqat-abu",
    title: "3 Daqat",
    artist: "Abu ft. Yousra",
    language: "arabic",
    region: "middle-east",
    genres: ["arab-pop"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 2, romance: 2, tempo: 1 },
    scenarios: ["chill", "party"],
    chips: [{ emoji: "🌅", label: "Seaside" }, { emoji: "💘", label: "Heartbeat" }],
    popularity: 80,
  },
  {
    id: "ahwak-abdel-halim",
    title: "Ahwak",
    artist: "Abdel Halim Hafez",
    language: "arabic",
    region: "middle-east",
    genres: ["arab-pop"],
    era: "1960s",
    platforms: {},
    traits: { romance: 3, cinematic: 2, softness: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "🌹", label: "Golden age" }, { emoji: "💔", label: "Eternal yearning" }],
    popularity: 82,
  },

  /* ─────────── Portuguese / Brazilian ─────────── */
  {
    id: "vai-malandra-anitta",
    title: "Vai Malandra",
    artist: "Anitta",
    language: "portuguese",
    region: "brazil",
    genres: ["funk", "pop"],
    era: "2010s",
    platforms: {},
    traits: { energy: 2, tempo: 2, confidence: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "🎉", label: "Baile funk" }, { emoji: "👑", label: "Carioca confidence" }],
    popularity: 82,
  },
  {
    id: "sossego-tim-maia",
    title: "Sossego",
    artist: "Tim Maia",
    language: "portuguese",
    region: "brazil",
    genres: ["funk", "soul"],
    era: "1970s",
    platforms: {},
    traits: { warmth: 3, tempo: 1, softness: 1 },
    scenarios: ["chill"],
    chips: [{ emoji: "🌅", label: "Sunday groove" }, { emoji: "🕺", label: "Easy funk" }],
    popularity: 78,
  },
  {
    id: "baile-de-favela-mc-joao",
    title: "Baile de Favela",
    artist: "MC João",
    language: "portuguese",
    region: "brazil",
    genres: ["funk"],
    era: "2010s",
    platforms: {},
    traits: { energy: 3, tempo: 3, confidence: 2 },
    scenarios: ["party"],
    chips: [{ emoji: "🎉", label: "Baile" }, { emoji: "🔊", label: "Bass" }],
    popularity: 80,
  },
  {
    id: "trem-bala-ana-vilela",
    title: "Trem-Bala",
    artist: "Ana Vilela",
    language: "portuguese",
    region: "brazil",
    genres: ["pop", "folk"],
    era: "2010s",
    platforms: {},
    traits: { softness: 3, warmth: 2, cinematic: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "🚂", label: "Fleeting" }, { emoji: "🌅", label: "Grateful" }],
    popularity: 80,
  },
  {
    id: "show-das-poderosas-anitta",
    title: "Show das Poderosas",
    artist: "Anitta",
    language: "portuguese",
    region: "brazil",
    genres: ["funk", "pop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, energy: 2, tempo: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "💃", label: "Powerful" }, { emoji: "🔥", label: "Stage energy" }],
    popularity: 78,
  },

  /* ─────────── Thai ─────────── */
  {
    id: "sudpang-milli",
    title: "สุดปัง (Sudpang!)",
    artist: "MILLI",
    language: "thai",
    region: "thailand",
    genres: ["thai-pop", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 2, energy: 2, chaos: 1, tempo: 1 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "👑", label: "Bangkok flex" }, { emoji: "🌶️", label: "Spice" }],
    popularity: 75,
  },
  {
    id: "glad-ink-waruntorn",
    title: "ดีใจด้วยนะ (Glad)",
    artist: "INK WARUNTORN",
    language: "thai",
    region: "thailand",
    genres: ["thai-pop"],
    era: "2010s",
    platforms: {},
    traits: { softness: 2, romance: 2, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "💔", label: "Happy for you (not)" }, { emoji: "🪶", label: "Gentle ache" }],
    popularity: 76,
  },
  {
    id: "lover-boy-phum-viphurit",
    title: "Lover Boy",
    artist: "Phum Viphurit",
    language: "english",
    region: "thailand",
    genres: ["indie"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 2, softness: 1, romance: 1 },
    scenarios: ["chill"],
    chips: [{ emoji: "🌅", label: "Sunshine indie" }, { emoji: "🛵", label: "Breezy" }],
    popularity: 74,
  },
  {
    id: "tilly-birds-thai",
    title: "ฉันไม่ได้ (I Don't)",
    artist: "Tilly Birds",
    language: "thai",
    region: "thailand",
    genres: ["thai-pop", "indie"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 2, warmth: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "🌸", label: "Dreamy" }, { emoji: "💔", label: "Soft hurt" }],
    popularity: 74,
  },
  {
    id: "bowkylion-thai",
    title: "ชอบ (Like)",
    artist: "Bowkylion",
    language: "thai",
    region: "thailand",
    genres: ["thai-pop"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, softness: 2, warmth: 2 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "🌷", label: "Sweet" }, { emoji: "🪶", label: "Pure" }],
    popularity: 73,
  },

  /* ─────────── Rock / Metal (additional) ─────────── */
  {
    id: "yellow-coldplay",
    title: "Yellow",
    artist: "Coldplay",
    language: "english",
    region: "europe",
    genres: ["rock", "pop"],
    era: "2000s",
    platforms: {},
    traits: { romance: 3, softness: 2, cinematic: 1 },
    scenarios: ["sad", "chill", "drive"],
    chips: [{ emoji: "⭐", label: "Stars" }, { emoji: "💘", label: "Devoted" }],
    popularity: 88,
  },
  {
    id: "retrograde-james-blake",
    title: "Retrograde",
    artist: "James Blake",
    language: "english",
    region: "europe",
    genres: ["electronic", "r&b"],
    era: "2010s",
    platforms: {},
    traits: { darkness: 2, cinematic: 2, softness: 1, focus: 1 },
    scenarios: ["sad", "focus", "drive"],
    chips: [{ emoji: "🌑", label: "Liminal" }, { emoji: "🎬", label: "Heavy quiet" }],
    popularity: 76,
  },
  {
    id: "creep-radiohead",
    title: "Creep",
    artist: "Radiohead",
    language: "english",
    region: "europe",
    genres: ["rock", "indie"],
    era: "1990s",
    platforms: {},
    traits: { darkness: 2, romance: 2, cinematic: 1, chaos: 1 },
    scenarios: ["sad", "drive"],
    chips: [{ emoji: "💔", label: "Outsider" }, { emoji: "🎸", label: "Cathartic" }],
    popularity: 90,
  },

  /* ─────────── English – additional ─────────── */
  {
    id: "heat-waves-glass-animals",
    title: "Heat Waves",
    artist: "Glass Animals",
    language: "english",
    region: "europe",
    genres: ["indie", "pop"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 2, warmth: 1, cinematic: 1 },
    scenarios: ["sad", "chill", "drive"],
    chips: [{ emoji: "🌡️", label: "Haunted summer" }, { emoji: "💔", label: "Longing" }],
    popularity: 91,
  },
  {
    id: "happier-olivia-rodrigo",
    title: "happier",
    artist: "Olivia Rodrigo",
    language: "english",
    region: "north-america",
    genres: ["pop", "indie"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, softness: 2, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "💔", label: "Young ache" }, { emoji: "🪶", label: "Honest" }],
    popularity: 88,
  },
  {
    id: "drivers-license-olivia-rodrigo",
    title: "drivers license",
    artist: "Olivia Rodrigo",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2020s",
    platforms: {},
    traits: { romance: 3, softness: 3, cinematic: 1 },
    scenarios: ["sad", "drive"],
    chips: [{ emoji: "💔", label: "Devastating" }, { emoji: "🚗", label: "Catharsis" }],
    popularity: 90,
  },
  {
    id: "watermelon-sugar-harry-styles",
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    language: "english",
    region: "europe",
    genres: ["pop", "rock"],
    era: "2020s",
    platforms: {},
    traits: { warmth: 3, tempo: 2, romance: 1 },
    scenarios: ["chill", "party"],
    chips: [{ emoji: "☀️", label: "Summer" }, { emoji: "🌊", label: "Easy" }],
    popularity: 88,
  },
  {
    id: "seven-nation-army-white-stripes",
    title: "Seven Nation Army",
    artist: "The White Stripes",
    language: "english",
    region: "north-america",
    genres: ["rock"],
    era: "2000s",
    platforms: {},
    traits: { aggression: 2, energy: 2, confidence: 1, tempo: 1 },
    scenarios: ["gym", "drive"],
    chips: [{ emoji: "🎸", label: "Iconic riff" }, { emoji: "🥊", label: "Marching" }],
    popularity: 88,
  },
  {
    id: "lose-yourself-eminem",
    title: "Lose Yourself",
    artist: "Eminem",
    language: "english",
    region: "north-america",
    genres: ["hip-hop"],
    era: "2000s",
    platforms: {},
    traits: { aggression: 2, confidence: 3, energy: 3, focus: 1 },
    scenarios: ["gym", "drive"],
    chips: [{ emoji: "🎯", label: "One shot" }, { emoji: "⚡", label: "Do not miss" }],
    popularity: 90,
  },
  {
    id: "bad-guy-billie-eilish",
    title: "bad guy",
    artist: "Billie Eilish",
    language: "english",
    region: "north-america",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { confidence: 3, darkness: 2, chaos: 1 },
    scenarios: ["party", "drive"],
    chips: [{ emoji: "😏", label: "Deadpan villain" }, { emoji: "🖤", label: "Irresistible" }],
    popularity: 91,
  },
  {
    id: "shape-of-you-ed-sheeran",
    title: "Shape of You",
    artist: "Ed Sheeran",
    language: "english",
    region: "europe",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 2, tempo: 2, warmth: 1 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "💘", label: "Magnetic" }, { emoji: "🕺", label: "Dance-floor" }],
    popularity: 93,
  },
  {
    id: "stay-the-kid-laroi",
    title: "STAY",
    artist: "The Kid LAROI & Justin Bieber",
    language: "english",
    region: "north-america",
    genres: ["pop", "hip-hop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 3, tempo: 3, romance: 1 },
    scenarios: ["party", "drive", "gym"],
    chips: [{ emoji: "⚡", label: "Non-stop" }, { emoji: "🔥", label: "2021 anthem" }],
    popularity: 91,
  },
  {
    id: "bohemian-rhapsody-queen",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    language: "english",
    region: "europe",
    genres: ["rock"],
    era: "1970s",
    platforms: {},
    traits: { cinematic: 3, chaos: 2, confidence: 2, energy: 2 },
    scenarios: ["drive", "party"],
    chips: [{ emoji: "🎬", label: "Opera-rock" }, { emoji: "🌪️", label: "Everything" }],
    popularity: 93,
  },
  {
    id: "no-sleep-til-brooklyn-beastie",
    title: "Fight For Your Right",
    artist: "Beastie Boys",
    language: "english",
    region: "north-america",
    genres: ["hip-hop", "rock"],
    era: "1980s",
    platforms: {},
    traits: { energy: 3, chaos: 2, confidence: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "🎉", label: "Timeless" }, { emoji: "🌪️", label: "Rowdy" }],
    popularity: 84,
  },
  {
    id: "perfect-ed-sheeran",
    title: "Perfect",
    artist: "Ed Sheeran",
    language: "english",
    region: "europe",
    genres: ["pop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 3, softness: 2, warmth: 2 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "💘", label: "Perfect" }, { emoji: "🌅", label: "Golden" }],
    popularity: 87,
  },

  /* ─────────── Korean – additional ─────────── */
  {
    id: "attention-newjeans",
    title: "Attention",
    artist: "NewJeans",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 2, tempo: 1, warmth: 1 },
    scenarios: ["chill", "focus"],
    chips: [{ emoji: "👀", label: "Hypnotic" }, { emoji: "🪶", label: "Breezy" }],
    popularity: 84,
  },
  {
    id: "eight-iu-suga",
    title: "eight",
    artist: "IU ft. Suga",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop", "pop"],
    era: "2020s",
    platforms: {},
    traits: { softness: 2, romance: 1, warmth: 2, cinematic: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "🌸", label: "Nostalgic" }, { emoji: "💘", label: "Collab" }],
    popularity: 83,
  },
  {
    id: "pink-venom-blackpink",
    title: "Pink Venom",
    artist: "BLACKPINK",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 3, aggression: 1, energy: 2, darkness: 1 },
    scenarios: ["gym", "party"],
    chips: [{ emoji: "🐍", label: "Lethal" }, { emoji: "👑", label: "Pink throne" }],
    popularity: 86,
  },
  {
    id: "after-like-ive",
    title: "After LIKE",
    artist: "IVE",
    language: "korean",
    region: "south-korea",
    genres: ["k-pop"],
    era: "2020s",
    platforms: {},
    traits: { confidence: 2, tempo: 2, energy: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "🌀", label: "I Will Survive-ified" }, { emoji: "🕺", label: "Disco-pop" }],
    popularity: 82,
  },

  /* ─────────── Japanese – additional ─────────── */
  {
    id: "yoru-ni-kakeru-yoasobi",
    title: "夜に駆ける (Yoru ni Kakeru)",
    artist: "YOASOBI",
    language: "japanese",
    region: "japan",
    genres: ["j-pop"],
    era: "2020s",
    platforms: {},
    traits: { energy: 2, tempo: 2, cinematic: 2, romance: 1 },
    scenarios: ["drive", "sad"],
    chips: [{ emoji: "🌙", label: "Midnight sprint" }, { emoji: "💔", label: "Rush" }],
    popularity: 86,
  },
  {
    id: "homura-lisa",
    title: "炎 (Homura)",
    artist: "LiSA",
    language: "japanese",
    region: "japan",
    genres: ["j-pop", "rock"],
    era: "2020s",
    platforms: {},
    traits: { cinematic: 3, energy: 2, romance: 2 },
    scenarios: ["drive", "gym", "sad"],
    chips: [{ emoji: "🔥", label: "Kimetsu" }, { emoji: "🎬", label: "Anime finale" }],
    popularity: 86,
  },

  /* ─────────── Spanish – additional ─────────── */
  {
    id: "con-calma-daddy-yankee",
    title: "Con Calma",
    artist: "Daddy Yankee & Snow",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton", "pop"],
    era: "2010s",
    platforms: {},
    traits: { tempo: 2, energy: 2, warmth: 2 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "🌴", label: "Tropical" }, { emoji: "🕺", label: "Easy bop" }],
    popularity: 85,
  },
  {
    id: "shakira-waka-waka",
    title: "Waka Waka (This Time for Africa)",
    artist: "Shakira",
    language: "spanish",
    region: "latin-america",
    genres: ["pop", "afrobeats"],
    era: "2010s",
    platforms: {},
    traits: { energy: 3, warmth: 2, confidence: 2, tempo: 2 },
    scenarios: ["party", "gym"],
    chips: [{ emoji: "🌍", label: "Global" }, { emoji: "🏆", label: "Anthem" }],
    popularity: 87,
  },
  {
    id: "despacito-luis-fonsi",
    title: "Despacito",
    artist: "Luis Fonsi ft. Daddy Yankee",
    language: "spanish",
    region: "latin-america",
    genres: ["reggaeton", "pop"],
    era: "2010s",
    platforms: {},
    traits: { romance: 2, tempo: 2, warmth: 2 },
    scenarios: ["party", "chill"],
    chips: [{ emoji: "💘", label: "Slow burn" }, { emoji: "🌴", label: "Summer" }],
    popularity: 92,
  },

  /* ─────────── Hindi – additional ─────────── */
  {
    id: "jai-ho-ar-rahman",
    title: "Jai Ho",
    artist: "A.R. Rahman",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2000s",
    platforms: {},
    traits: { cinematic: 3, energy: 2, confidence: 1 },
    scenarios: ["party", "drive"],
    chips: [{ emoji: "🏆", label: "Oscar-winning" }, { emoji: "🎬", label: "Epic" }],
    popularity: 84,
  },
  {
    id: "srivalli-javed-ali",
    title: "Srivalli",
    artist: "Javed Ali",
    language: "hindi",
    region: "south-asia",
    genres: ["bollywood"],
    era: "2020s",
    platforms: {},
    traits: { cinematic: 2, romance: 2, warmth: 1 },
    scenarios: ["chill", "sad", "drive"],
    chips: [{ emoji: "💘", label: "Pushpa" }, { emoji: "🌄", label: "Sweeping" }],
    popularity: 84,
  },

  /* ─────────── Afrobeats – additional ─────────── */
  {
    id: "gelato-omah-lay",
    title: "Godly",
    artist: "Omah Lay",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, softness: 2, warmth: 2 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "🌅", label: "Afrobeats tender" }, { emoji: "💘", label: "Vulnerable" }],
    popularity: 78,
  },
  {
    id: "ojuelegba-wizkid",
    title: "Ojuelegba",
    artist: "Wizkid",
    language: "english",
    region: "nigeria",
    genres: ["afrobeats"],
    era: "2010s",
    platforms: {},
    traits: { warmth: 3, cinematic: 1, softness: 1 },
    scenarios: ["chill"],
    chips: [{ emoji: "🌍", label: "Lagos origin" }, { emoji: "🕊️", label: "Roots" }],
    popularity: 80,
  },

  /* ─────────── Brazilian – additional ─────────── */
  {
    id: "garota-de-ipanema-joao-gilberto",
    title: "Garota de Ipanema",
    artist: "João Gilberto",
    language: "portuguese",
    region: "brazil",
    genres: ["bossa-nova", "jazz"],
    era: "1960s",
    platforms: {},
    traits: { softness: 3, warmth: 3, romance: 2 },
    scenarios: ["chill", "focus"],
    chips: [{ emoji: "🌊", label: "Bossa nova" }, { emoji: "☀️", label: "Timeless" }],
    popularity: 82,
  },

  /* ─────────── Arabic – additional ─────────── */
  {
    id: "habibi-mishaal-khairy",
    title: "Habibi",
    artist: "Mishaal Khairy",
    language: "arabic",
    region: "middle-east",
    genres: ["arab-pop"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, warmth: 2, softness: 1 },
    scenarios: ["chill", "sad"],
    chips: [{ emoji: "💘", label: "My love" }, { emoji: "🌅", label: "Middle Eastern pop" }],
    popularity: 76,
  },

  /* ─────────── Jazz – additional ─────────── */
  {
    id: "autumn-leaves-bill-evans",
    title: "Autumn Leaves",
    artist: "Bill Evans",
    language: "instrumental",
    region: "north-america",
    genres: ["jazz"],
    era: "1960s",
    platforms: {},
    traits: { softness: 3, focus: 2, cinematic: 1, romance: 1 },
    scenarios: ["focus", "chill", "sad"],
    chips: [{ emoji: "🍂", label: "Classic" }, { emoji: "🎹", label: "Piano trio" }],
    popularity: 78,
  },
  {
    id: "so-what-miles-davis",
    title: "So What",
    artist: "Miles Davis",
    language: "instrumental",
    region: "north-america",
    genres: ["jazz"],
    era: "1960s",
    platforms: {},
    traits: { focus: 3, confidence: 2, softness: 1 },
    scenarios: ["focus", "chill"],
    chips: [{ emoji: "🎷", label: "Modal jazz" }, { emoji: "🧠", label: "Cool" }],
    popularity: 80,
  },

  /* ─────────── Lo-fi – additional ─────────── */
  {
    id: "snowfall-oneheart",
    title: "snowfall",
    artist: "Øneheart x reidenshi",
    language: "instrumental",
    region: "global",
    genres: ["lo-fi", "electronic"],
    era: "2020s",
    platforms: {},
    traits: { softness: 3, focus: 2, darkness: 1 },
    scenarios: ["focus", "sad", "chill"],
    chips: [{ emoji: "❄️", label: "Crystalline" }, { emoji: "🧘", label: "Peace" }],
    popularity: 76,
  },

  /* ─────────── Thai – additional ─────────── */
  {
    id: "bedroom-audio-thai",
    title: "กลับมา (Come Back)",
    artist: "Bedroom Audio",
    language: "thai",
    region: "thailand",
    genres: ["thai-pop", "indie"],
    era: "2020s",
    platforms: {},
    traits: { romance: 2, softness: 2, darkness: 1 },
    scenarios: ["sad", "chill"],
    chips: [{ emoji: "🌙", label: "Bedroom indie" }, { emoji: "💔", label: "Yearning" }],
    popularity: 72,
  },

  /* ─────────── EDM / Electronic – additional ─────────── */
  {
    id: "one-more-time-daft-punk",
    title: "One More Time",
    artist: "Daft Punk",
    language: "english",
    region: "europe",
    genres: ["edm", "funk"],
    era: "2000s",
    platforms: {},
    traits: { energy: 3, warmth: 2, tempo: 2, confidence: 1 },
    scenarios: ["party"],
    chips: [{ emoji: "🕺", label: "French house" }, { emoji: "✨", label: "Euphoric" }],
    popularity: 88,
  },
  {
    id: "lean-on-major-lazer",
    title: "Lean On",
    artist: "Major Lazer & DJ Snake",
    language: "english",
    region: "global",
    genres: ["edm", "pop"],
    era: "2010s",
    platforms: {},
    traits: { energy: 2, tempo: 2, warmth: 2 },
    scenarios: ["party", "drive"],
    chips: [{ emoji: "🌍", label: "Global smash" }, { emoji: "💨", label: "Airborne" }],
    popularity: 87,
  },
];

export const FALLBACK_CATALOG: Catalog = {
  version: FALLBACK_CATALOG_VERSION,
  songs: FALLBACK_SONGS,
  vibeCards: FALLBACK_VIBE_CARDS,
  scenarios: FALLBACK_SCENARIOS,
};
